import type { OfflineRecord } from "./offlineStore";

export const CUSTOMER_REQUEST_SCHEMA = "global1881-offline-customer-request-v1";
export type CustomerRequestDetails = { schema: typeof CUSTOMER_REQUEST_SCHEMA; operation: "sale" | "rent"; sourceClientRecordId?: string; clientReference: string; location: string; propertyType: string; minBudget: number; maxBudget: number; timing: string; notes: string; status: "open" | "paused" | "closed" };
export type PortfolioCandidate = { recordId: string; advisorUserId: string; operation: "sale" | "rent" | "both"; location: string; propertyType: string; price: number; source: "property" | "authority" | "rental" };
export type RequestMatch = { requestRecordId: string; requesterUserId: string; operation: "sale" | "rent"; candidateRecordId: string; portfolioAdvisorUserId: string; location: string; propertyType: string; price: number; score: number; reasons: string[] };
const normalize = (value: string) => value.toLocaleLowerCase("tr-TR").replace(/[^a-z0-9çğıöşü\s]/g, " ").replace(/\s+/g, " ").trim();
const money = (value: unknown) => Number(String(value ?? "").replace(/[^0-9]/g, "")) || 0;
export function parseCustomerRequest(record: OfflineRecord): CustomerRequestDetails | null { if (record.entity !== "request") return null; try { const value = JSON.parse(record.details) as Partial<CustomerRequestDetails>; return value.schema === CUSTOMER_REQUEST_SCHEMA && (value.operation === "sale" || value.operation === "rent") && typeof value.location === "string" ? { schema: CUSTOMER_REQUEST_SCHEMA, operation: value.operation, sourceClientRecordId: value.sourceClientRecordId, clientReference: value.clientReference ?? "", location: value.location, propertyType: value.propertyType ?? "", minBudget: Math.max(0, Number(value.minBudget) || 0), maxBudget: Math.max(0, Number(value.maxBudget) || 0), timing: value.timing ?? "", notes: value.notes ?? "", status: value.status ?? "open" } : null; } catch { return null; } }
export function portfolioCandidates(records: OfflineRecord[]): PortfolioCandidate[] { return records.flatMap<PortfolioCandidate>((record) => { try { const value = JSON.parse(record.details) as Record<string, unknown>; if (record.entity === "property") return [{ recordId: record.id, advisorUserId: record.userId, operation: "both", location: `${record.title} ${record.details}`, propertyType: String(value.propertyType ?? value.type ?? ""), price: money(record.amount ?? value.price ?? value.monthlyRent), source: "property" }]; if (record.entity !== "contract") return []; const schema = String(value.schema ?? ""); if (schema.startsWith("global1881-offline-authority")) return [{ recordId: record.id, advisorUserId: record.userId, operation: value.mode === "rent" ? "rent" : "sale", location: String(value.propertyAddress ?? ""), propertyType: String(value.propertyType ?? ""), price: money(value.price), source: "authority" }]; if (schema.startsWith("global1881-offline-rental")) return [{ recordId: record.id, advisorUserId: record.userId, operation: "rent", location: String(value.propertyAddress ?? ""), propertyType: String(value.propertyType ?? ""), price: money(value.monthlyRent), source: "rental" }]; } catch { /* bozuk kayıt eşleştirmeyi engellemez */ } return []; }); }
export function findCustomerRequestMatches(records: OfflineRecord[]): RequestMatch[] { const requests = records.flatMap((record) => { const request = parseCustomerRequest(record); return request?.status === "open" ? [{ record, request }] : []; }); const candidates = portfolioCandidates(records); return requests.flatMap(({ record, request }) => candidates.flatMap((candidate) => { if (candidate.advisorUserId === record.userId || (candidate.operation !== "both" && candidate.operation !== request.operation)) return []; const locationRequest = normalize(request.location), locationCandidate = normalize(candidate.location); const locationMatch = locationRequest.length >= 3 && (locationCandidate.includes(locationRequest) || locationRequest.includes(locationCandidate)); if (!locationMatch) return []; const typeRequest = normalize(request.propertyType), typeCandidate = normalize(candidate.propertyType); const typeMatch = !typeRequest || typeCandidate.includes(typeRequest) || typeRequest.includes(typeCandidate); if (!typeMatch) return []; const priceMatch = !candidate.price || ((!request.minBudget || candidate.price >= request.minBudget) && (!request.maxBudget || candidate.price <= request.maxBudget)); if (!priceMatch) return []; const reasons = ["Konum uyumu", ...(typeRequest ? ["Nitelik uyumu"] : []), ...(candidate.price ? ["Bütçe aralığı"] : [])]; return [{ requestRecordId: record.id, requesterUserId: record.userId, operation: request.operation, candidateRecordId: candidate.recordId, portfolioAdvisorUserId: candidate.advisorUserId, location: candidate.location, propertyType: candidate.propertyType, price: candidate.price, score: reasons.length, reasons }]; })); }
