import type { OfflineRentalDetails } from "./rentalContract";

export const RENTAL_CONDITIONS_TEMPLATE_VERSION = "global1881-rental-conditions-2026-08-v1";

const RESIDENTIAL = [
  "TESLİM VE DEMİRBAŞLAR\nMecur, Kiracı'ya sağlam, tam ve kullanılmaya elverişli şekilde teslim edilmiştir. Demirbaşlar temiz, çalışır ve sağlam vaziyette teslim edilmiş olup, teslim anındaki durum işbu sözleşmenin eki olan Teslim Tutanağı ve Demirbaş Listesi'nde (Ek-1) tespit edilmiştir. Kiracı, mecurun kendisine teslimi anında görünür bir ayıbının bulunmadığını kabul ve beyan eder; olağan incelemeyle tespit edilemeyecek gizli ayıplar bu beyanın dışındadır.",
  "DEVİR, ALT KİRA VE TURİZM AMAÇLI KİRALAMA YASAĞI\nKiracı, Kiraya Verenin yazılı izni olmadan işbu Kira Sözleşmesinden doğan haklarının bir kısmını veyahut tamamını başkasına devir veya temlik edemeyeceği gibi; alt kiraya da veremez. Kiracı, mecuru 7464 sayılı Kanun kapsamında turizm amaçlı olarak günlük veya kısa süreli şekilde üçüncü kişilere kiraya veremez; bu yasağa aykırılık, ayrıca ihtara gerek olmaksızın sözleşmeye aykırılık ve tahliye sebebi sayılır.",
  "KULLANIM AMACI\nKiracı, mecuru yalnızca mesken/konut olarak, kendisi ve birlikte yaşadığı kişilerle sınırlı şekilde kullanacak olup, başka amaçlarla kullanamaz.{{kisiSayisiCumle}} Kiracı, mecuru ticari, sınai veya mesleki faaliyet için kullanamayacağı gibi; Kiraya Verenin yazılı izni olmaksızın ticari işletme veya şirket için adres olarak gösteremez ve tescil ettiremez.",
  "KİRA BEDELİ VE ÖDEME\nAylık kira bedeli net {{kira}}'dır. İlk kira bedelinin son ödeme tarihi {{ilkVade}} olup, bu tarih sözleşme tarihinden en geç 5 (beş) gün sonradır. Sonraki kira bedelleri EFT ya da her türlü gönderme masrafları Kiracı'ya ait olmak üzere her ayın en geç {{odemeGun}}. günü Kiraya Veren'in yukarıda belirtilen banka hesabına Kiracı tarafından transfer edilecektir. Kira bedeli ve sair giderlerin zamanında ödenmemesi halinde 6098 sayılı Türk Borçlar Kanunu'nun ve 634 sayılı Kat Mülkiyeti Kanunu'nun ilgili hükümleri uygulanacaktır.",
  "TEMERRÜT VE İHTAR\nKira bedelinin süresinde ödenmemesi hâlinde Kiracı, gecikilen tutar üzerinden yasal temerrüt faizi öder. Kiracının ödemede temerrüde düşmesi hâlinde Kiraya Veren, 6098 sayılı Türk Borçlar Kanunu m. 315 uyarınca en az otuz günlük süre vererek borcun ifasını yazılı olarak ihtar eder; bu süre içinde ifa edilmezse sözleşmeyi feshedebilir. Kiraya Verenin, bir kira yılı içinde iki haklı yazılı ihtara dayalı tahliye davası açma hakkı (TBK m. 352/2) saklıdır.",
  "İKİ HAKLI İHTAR VE TAHLİYE\nKiracının bir kira yılı içinde iki ayın kira bedelini zamanında ödemeyerek Kiraya Veren tarafından kendisine iki haklı yazılı ihtar gönderilmesine sebep olması hâlinde Kiraya Veren, 6098 sayılı Türk Borçlar Kanunu m. 352/2 uyarınca, ihtarların yapıldığı kira yılının bitiminden başlayarak bir ay içinde açacağı dava ile kiralananın tahliyesini talep edebilir.",
  "DEPOZİTO\nKiracı, sözleşmeden doğabilecek borçlarına karşılık Kiraya Verene {{depozito}} tutarında depozito ödemiştir. Depozito hiçbir şekilde kira bedeline mahsup edilemez; Kiracı, son ay veya aylara ait kira borcunu depozitodan düşemez. Kira ilişkisinin sona ermesi hâlinde, mecurun hasarsız teslim edildiğinin, abonelik borçlarının kapatıldığının ve kira borcu bulunmadığının tespiti üzerine depozito, alındığı para cinsinden ve en geç 15 (on beş) gün içinde Kiracıya iade edilir. Kiracının sorumlu olduğu, belgelendirilmiş hasar ve borçlar depozitodan mahsup edilerek bakiyesi iade edilir.",
  "ABONELİKLER\nKiracı, kullandığı doğalgaz, elektrik, su, kablolu TV, özel abonelikler, internet, telefon gibi hizmetlerin masraflarını ödeyecek olup; mecurun kullanımı ile ilgili ve mecurun kullanımı sırasında alınması gereken tüm abonelikler Kiracı adına alınacaktır. Kiracı, kira ilişkisinin sona ermesi hâlinde adına açtırdığı tüm abonelikleri kapatmak ve ilişik kesme belgelerini Kiraya Verene ibraz etmekle yükümlüdür.",
  "BAKIM VE ONARIM\nKiraya Veren mecurun ana demirbaş ve tesisatlarında Kiracının kontrolü dışında ve kiracının kusuru olmaksızın oluşabilecek hasar ve zararların giderilmesinden, Kiracı ise kullanım sırasında oluşabilecek küçük çaptaki arızalar, normal kullanımdan kaynaklanan eskime ve yıpranmalar ile her durumda kendi kusuru ile oluşabilecek zararların giderilmesinden sorumludur. Kiracının sorumluluğundaki küçük bakım ve onarımlar; musluk ve conta, priz ve ampul değişimi, kapı-pencere donanımı, gider temizliği gibi olağan kullanım unsurlarını kapsar. Kiracı, giderilmesi Kiraya Verene ait olan bir arıza veya ayıbı fark ettiğinde durumu gecikmeksizin Kiraya Verene bildirmekle yükümlüdür. Bildirimde bulunulmaması nedeniyle zararın artması hâlinde, artan kısımdan Kiracı sorumludur.",
  "MECURUN İADESİ\nNormal aşınma ve eskimenin dışında, Kiracı mecuru, teslim aldığı şekilde aynen demirbaşları ve mütemmim cüzleri ile birlikte temiz, tam, tesisatları çalışır ve kullanılabilir vaziyette teslim etmek zorundadır. Mecurun iadesi sırasında taraflar, mecurun ve demirbaşların durumunu birlikte gözden geçirerek Çıkış Tutanağı düzenler. Kiraya Veren, Kiracının sorumlu olduğu eksiklik ve hasarları gecikmeksizin yazılı olarak bildirir; olağan incelemeyle tespit edilemeyecek gizli ayıplar bu kuralın dışındadır.",
  "TADİLAT VE DEĞİŞİKLİKLER\nKiracı, mecurun içinde veya dışında kısmen veya tamamen tadilat, dekorasyon veya sabit tesisat değişikliği yapmadan önce Kiraya Verenin yazılı iznini almak zorundadır. İzinsiz yapılan değişiklikleri Kiracı, Kiraya Verenin talebi üzerine kendi masrafıyla eski hâline getirmekle yükümlüdür. İzinle yapılan ve sökülmesi mecura zarar verecek nitelikteki sabit tadilatlar, aksi yazılı olarak kararlaştırılmadıkça sözleşmenin sonunda bedelsiz olarak mecurda kalır; Kiracı bu değişiklikler için bedel veya denkleştirme talep edemez.",
  "KİRA SÜRESİ VE UZAMA\nKira süresi {{sure}} olup, {{basla}} tarihinde başlar ve {{bitis}} tarihinde sona erer. Sürenin bitiminden en az 1 (bir) ay önce yazılı fesih bildirimi yapılmadığı takdirde sözleşme aynı koşullarla bir yıl uzar. Sözleşmenin sona erdirilmesine ve tahliyeye ilişkin hususlarda 6098 sayılı Türk Borçlar Kanunu'nun ilgili hükümleri uygulanır.",
  "İLAN VE GEZDİRME\nKiracı; sözleşmenin sona ereceğinin bildirilmesi veya mecurun satışa ya da yeniden kiraya verilmesine karar verilmesi hâlinde, Kiraya Verenin ve yetkilendirdiği emlak danışmanının mecurun iç ve dış fotoğraflarını çekmesine, bu görsellerle ilan yayınlanmasına ve alıcı veya kiracı adaylarına mecuru göstermesine izin vermekle yükümlüdür. Gezdirme, kendisine önceden haber verilmek kaydıyla haftada 2 (iki) gün ve makul saatlerde yapılır. Kiracının bu yükümlülüğe uymaması sözleşmeye aykırılık teşkil eder.",
  "TAHLİYE ZAMANI VE TESLİM\nSözleşmenin sona ermesi veya feshi hâlinde Kiracı, mecuru sözleşmenin sona erdiği tarihte boşaltarak, demirbaşları ve mütemmim cüzleriyle birlikte temiz ve kullanılabilir vaziyette Kiraya Verene teslim etmek zorundadır. Mecurda olağan kullanım sınırlarını aşan kirlenme, leke, delik veya hasar bulunması hâlinde boya, badana ve onarım masrafları Kiracıya aittir.",
  "KİRA ARTIŞI\nKira bedeli; her kira dönemi sonunda TÜİK tarafından açıklanan Yurt İçi Tüketici Fiyat Endeksindeki (TÜFE) on iki aylık ortalamalara göre değişim oranı üzerinden artırılacaktır. Bu maddede düzenlenen artırım oranı için Kiraya Veren tarafından önceden herhangi bir surette bildirim yapılmasına gerek olmaksızın, açıklanan verilere göre Kiracı tarafından artırım yapılarak ödeme yapılacaktır. Verilerin geç açıklanması halinde, önceki dönemlere göre oluşacak kira bedeli farkları da ilk dönem kira bedeline eklenerek ödenecektir. Beş yıldan uzun süreli veya beş yıldan sonra yenilenen kira dönemlerinde ve bundan sonraki her beş yılın sonunda, yeni kira yılında uygulanacak kira bedeli, tarafların anlaşamaması hâlinde 6098 sayılı Türk Borçlar Kanunu m. 344/3 uyarınca kiralananın durumu ve emsal kira bedelleri göz önünde tutularak hâkim tarafından belirlenir.",
  "GİDERLER, SİGORTA VE KURALLARA UYUM\nMecurun kullanımından doğan giderler ile olağan aidat ve ortak gider payları Kiracıya aittir. Emlak vergisi, zorunlu deprem sigortası (DASK), bina sigortası ile ana yapının ortak yerlerine ilişkin büyük onarım, yenileme ve demirbaş nitelikli giderler (kazan, asansör, çatı, dış cephe yenilenmesi gibi) Kiraya Verene aittir. Kiracı; 6098 sayılı Türk Borçlar Kanunu ve 634 sayılı Kat Mülkiyeti Kanunu hükümleri ile bina/site yönetim planına ve kat malikleri kurulu kararlarına uymak zorundadır. Kiracının bu hükümlere aykırı davranması sözleşmeye aykırılık ve tahliye nedenidir.",
  "TEBLİGAT\nBu kira sözleşmesi uyarınca, tarafların birbirlerinin yukarıdaki adreslerine yapacakları her türlü ihbar veya talep yazılı olmalıdır. Kiracı ve Kiraya Veren tebligat adreslerindeki değişiklikleri, değişiklikten itibaren bir ay içerisinde yazılı olarak diğer tarafa bildirmek zorundadır. Aksi takdirde bu adreslere yapılan tebligatlar, her durumda geçerli sayılacaktır.",
  "ERKEN TAHLİYE\nKiracı, sözleşme süresi dolmadan mecuru mahkemece kabul görmüş bir mücbir sebep olmaksızın tahliye ederse, kalan kira bedellerinin tamamı muaccel olmayıp; 2 aylık kira bedeli ile bu süreye ait ortak gider ve aidatları tazminat olarak peşinen öder. Mecurun daha önce yeniden kiraya verilmesi halinde kiracının sorumluluğu yeni kiranın başlangıç tarihinde sona erer. Kiraya Veren, mecuru en kısa sürede yeniden kiraya vermek için makul gayreti göstermekle yükümlüdür.",
  "BÖLÜNEBİLİRLİK\nİşbu Kira Sözleşmesi'nin herhangi bir maddesinin herhangi bir sebeple geçersiz olduğuna hükmedilmesi halinde, sözleşmenin diğer hükümleri geçerliliğini koruyacaktır.",
  "VERGİ VE STOPAJ\nİşbu sözleşme nedeniyle damga vergisi doğması hâlinde bu vergi Kiracı tarafından ödenir. Kiracının gelir veya kurumlar vergisi mükellefi olması hâlinde, kira ödemeleri üzerinden yapılması gereken vergi kesintisi (stopaj) Kiracı tarafından beyan edilip ödenir ve makbuz örneği Kiraya Verene iletilir. Emlak vergisi ve mülkiyetten doğan yükümlülükler Kiraya Verene aittir.",
  "[SON]UYUŞMAZLIKLARIN ÇÖZÜMÜ\nKira ilişkisinden kaynaklanan uyuşmazlıklarda, ilamsız icra yoluyla tahliye hariç olmak üzere, dava açılmadan önce arabulucuya başvurulması dava şartıdır. Anlaşma sağlanamaması hâlinde {{mahkeme}} Mahkemeleri ve İcra Daireleri yetkilidir.",
  "[SON]UYGULANACAK HÜKÜMLER\nİşbu Kira Sözleşmesi'nde hüküm bulunmayan hallerde, 6098 sayılı Türk Borçlar Kanunu, 634 sayılı Kat Mülkiyeti Kanunu ve niteliğine uygun düştüğü sürece diğer yasal mevzuat hükümleri uygulanacaktır.",
  "[SON][KEFIL]KEFALET\nİşbu sözleşmede kefil gösterilmesi tarafların anlaşmasına bağlıdır. Kefil gösterilmesi hâlinde kefil; kefil olduğu azami tutarı, kefalet tarihini ve müteselsil kefil sıfatıyla yükümlülük altına girdiğini kendi el yazısıyla yazarak imzalar (TBK m. 583). Kefil evli ise kefaletin geçerliliği, eşin yazılı rızasının kefalet anında veya öncesinde alınmasına bağlıdır. Ancak kefil; ticaret siciline kayıtlı bir ticari işletmenin sahibi ya da bir ticaret şirketinin ortağı veya yöneticisi sıfatıyla ve işletme veya şirketle ilgili olarak kefil oluyorsa eşin rızası aranmaz (TBK m. 584/3).",
  "[SON]YÜRÜRLÜK\nİşbu kira sözleşmesi; 2 (iki) asıl nüsha ve {{maddeSayisi}} hususi şarttan ibaret olup; {{tarih}} tarihinde {{yer}}'da, taraflarca imzalanarak yürürlüğe girmiştir.",
];

const COMMERCIAL = [
  "KİRA SÜRESİ\nSözleşme süresi, {{basla}} tarihinde başlar ve {{bitis}} tarihinde sona erer ({{sure}}). Sözleşme süresinin bitiminden en az on beş gün önce taraflardan biri yazılı fesih bildiriminde bulunmadığı takdirde, TBK m. 347 uyarınca sözleşme, aynı şartlarla bir yıl süreyle kendiliğinden uzar. Kiracı, on yıllık uzama süresi sonunda TBK m. 347/2 uyarınca sözleşmeyi bildirim yoluyla sona erdirebilir. Kiraya Veren ise on yıllık uzama süresi sonunda, bu süreyi izleyen her uzama yılının bitiminden en az üç ay önce bildirimde bulunmak koşuluyla, herhangi bir sebep göstermeksizin sözleşmeye son verebilir (TBK m. 347/1).",
  "KİRA BEDELİ VE ÖDEME ŞEKLİ\nAylık kira bedeli net {{kira}} olup {{kdv}}. İlk kira bedelinin son ödeme tarihi {{ilkVade}} olup, bu tarih sözleşme tarihinden en geç 5 (beş) gün sonradır. Sonraki kira bedelleri her ayın {{odemeGun}}. günü, peşin olarak, Kiraya Verenin {{iban}} numaralı banka hesabına ödenir. Kira bedelinin ödeme yerinin değiştirilmesi, ilgili tarafça diğer tarafa yazılı olarak bildirilir. Kira bedelinin süresinde ödenmemesi hâlinde, geciken her gün için Kiracı, gecikilen tutara yasal aylık temerrüt faiz oranını aşmamak kaydıyla temerrüt faizi öder. Kiraya Verenin bu nedenle fesih hakkı saklıdır.",
  "KİRA BEDELİNİN ARTIRILMASI\nYenilenen kira dönemlerinde uygulanacak kira bedeli artış oranı, TBK m. 344 uyarınca bir önceki kira yılında Türkiye İstatistik Kurumu (TÜİK) tarafından açıklanan Tüketici Fiyat Endeksi'ndeki (TÜFE) on iki aylık ortalamalara göre değişim oranını geçemez. Taraflar, işbu kanuni üst sınırı aşmayacak şekilde yeni dönem kira bedelini her kira yılı başında birlikte belirler. Taraflar arasında mutabakat sağlanamaması hâlinde, kira bedeli TBK m. 344/2 uyarınca hâkim tarafından belirlenir.",
  "GÜVENCE BEDELİ (DEPOZİTO)\nKiracı, sözleşmeden doğabilecek borçlarına karşılık Kiraya Verene {{depozito}} güvence bedeli öder. TBK m. 342 uyarınca bu bedel üç aylık kirayı aşamaz; aşan kısım geçersizdir. Güvence bedeli, Kiracının yazılı onayı olmadan çekilmemek üzere bankada müşterek imzalı bir vadeli hesapta tutulur, kira bedeline mahsup edilemez ve hesap neması Kiracıya aittir; dekontu bir ay içinde Kiracıya teslim edilir. Kiralananın borçsuz ve hasarsız teslim edilmesi hâlinde güvence bedeli, nemasıyla birlikte en geç on beş gün içinde iade edilir. Kiracının sorumlu olduğu, belgelendirilmiş hasar veya borç varsa bu tutar güvence bedelinden mahsup edilip bakiyesi iade edilir.",
  "KİRALANANIN TESLİMİ VE İADESİ\nKiralanan, işbu sözleşmenin eki olan Teslim Tutanağı ve Demirbaş Listesi'nde (Ek-1) belirtilen durum ve donanımla, kullanıma elverişli ve ayıpsız şekilde Kiracıya teslim edilir. Taraflar, teslim anında Kiralananın durumunu birlikte tespit ederek tutanak altına alır. Kiracı, Kiralananı teslim aldığı durumda geri vermekle yükümlüdür; ancak sözleşmeye uygun kullanım nedeniyle oluşan olağan yıpranma ve eskimelerden sorumlu değildir. Kiraya Veren, geri alma sırasında Kiralananın durumunu gözden geçirir; Kiracının sorumlu olduğu eksiklik ve ayıpları gecikmeksizin yazılı olarak bildirir. Bu bildirim yapılmadığı takdirde Kiracı sorumluluktan kurtulur; ancak olağan incelemeyle tespit edilemeyecek gizli ayıplar bu kuralın dışındadır.",
  "KULLANIM AMACI, İSKÂN VE RUHSAT\nKiralanan, münhasıran {{amac}} amacıyla kullanılacaktır. Kullanım amacının değiştirilmesi, Kiraya Verenin yazılı onayına tabidir. Kiralananın tapu kaydındaki niteliği {{tapuNitelik}} olup, yapı kullanma izni (iskân) durumu sözleşmenin imzalanmasından önce taraflarca kontrol edilmiştir. Kiraya Veren, taşınmazın malikliğine ve iskân durumuna ilişkin belgeleri Kiracıya ibraz eder. Kiracı, faaliyeti için gerekli işyeri açma ve çalışma ruhsatı ile diğer izin ve lisansları kendi sorumluluğunda ve masrafında temin eder. Kiracı, bu izinlerin alınabilirliğini sözleşmenin imzalanmasından önce ilgili belediye nezdinde araştırdığını ve teyit ettiğini beyan eder. Bu sebeple Kiracı, izinlerin sonradan alınamaması gerekçesiyle Kiraya Verenden tazminat talep edemez.",
  "DEVİR, ALT KİRA VE TEMLİK\nKiracı, Kiraya Verenin yazılı onayı olmaksızın kira ilişkisini üçüncü bir kişiye devredemez ve Kiralananın tamamını veya bir kısmını alt kiraya veremez. TBK m. 323 uyarınca Kiraya Veren, haklı bir sebep bulunmadıkça bu onayı vermekten kaçınamaz. Onayın haksız olarak reddedildiğinin tespiti hâlinde, Kiracının bundan doğan zararlarının tazmini talep hakkı saklıdır. Kira ilişkisinin devri hâlinde, devreden Kiracı, TBK m. 323/2 uyarınca en fazla iki yıl süreyle devralanla birlikte müteselsilen sorumlu kalır.",
  "KİRACININ HAK VE YÜKÜMLÜLÜKLERİ\n• Kiralananı sözleşmeye ve kullanım amacına uygun, özenli biçimde kullanmak.\n• Kiralananın olağan kullanımından doğan küçük bakım ve onarım giderlerini (kapı-pencere donanımı, musluk, priz, ampul vb. günlük kullanım unsurları) karşılamak.\n• Kendisinin gidermekle yükümlü olmadığı ayıpları Kiraya Verene gecikmeksizin yazılı olarak bildirmek.\n• Kiralananın kullanımına ilişkin elektrik, su, doğalgaz, internet vb. abonelikleri kendi adına açtırmak ve düzenli olarak ödemek.\n• Kiraya Verenin veya yetkilendirdiği kişilerin, makul bir süre önceden haber vermek kaydıyla bakım, satış veya yeniden kiralama amacıyla Kiralananı gezip görmesine izin vermek.",
  "KİRAYA VERENİN HAK VE YÜKÜMLÜLÜKLERİ\n• Kiralananı sözleşmede öngörülen kullanıma elverişli, ayıpsız ve mevzuata uygun biçimde teslim etmek.\n• Kiralananın yapısal/esaslı unsurlarına ilişkin, Kiracının kullanımından kaynaklanmayan bakım ve onarımları kendi giderleriyle ve gecikmeksizin yaptırmak.\n• Kiralananın mülkiyetinden doğan emlak vergisi ve benzeri yükümlülükleri karşılamak.\n• Kiracının sözleşmeye uygun ve aralıksız kullanımını, haklı bir sebep ve önceden bildirim olmaksızın engellememek.\n• Üçüncü bir kişinin Kiralanan üzerinde Kiracının hakkıyla bağdaşmayan bir hak ileri sürmesi hâlinde, Kiracının bildirimi üzerine bu duruma karşı hukuki yollara başvurmak ve Kiracının bu sebeple uğradığı zararı gidermek. Kiraya Verenin bu maddedeki yükümlülüklerini yerine getirmemesi hâlinde Kiracı, TBK m. 305-308 hükümleri uyarınca ayıba ilişkin haklarını kullanabilir.",
  "TADİLAT VE DEĞİŞİKLİKLER\nKiracı, Kiralananda tadilat, dekorasyon veya sabit tesisat değişikliği yapmadan önce Kiraya Verenin yazılı onayını alır. Onaylanan tadilatların masrafları, aksi kararlaştırılmadıkça Kiracıya aittir. Sözleşmenin sona ermesi hâlinde, sökülmesi Kiralanana zarar verecek nitelikteki sabit tadilatlar, aksi yazılı olarak kararlaştırılmadıkça bedelsiz olarak Kiralananda kalır. Kiralananın olağan kullanımı kapsamında, binanın yapısını bozmayan küçük onarımlar (kilit, reze, badana vb.) Kiraya Verene ayrıca bildirim yapılmaksızın gerçekleştirilebilir; bu tür onarımların bedeli Kiraya Verenden talep edilemez.",
  "SİGORTA\nKiraya Veren, Kiralanana ilişkin Zorunlu Deprem Sigortasını (DASK) ve bina sigortasını (yangın, sel vb.) yaptırmak ve kira süresi boyunca geçerli tutmakla yükümlüdür. Kiracı, Kiralanan içindeki kendi demirbaş, emtia ve sabit dekorasyonuna ilişkin sigortayı kendi maliyetiyle yaptırmakla yükümlüdür. Sigorta poliçesinin bir örneği, sözleşme başlangıcından itibaren bir ay içinde Kiraya Verene ibraz edilir.",
  "VERGİ, RESİM, HARÇ VE STOPAJ\nVergi, resim, harç ve benzeri yükümlülükler aşağıdaki şekilde paylaşılır:\n• Damga vergisi: aksi yazılı olarak kararlaştırılmadıkça Taraflarca eşit karşılanır.\n• Kira stopajı: Kiracının gelir/kurumlar vergisi mükellefi olması hâlinde, brüt kira bedeli üzerinden kesilip beyan edilir ve makbuz örneği Kiraya Verene iletilir.\n• Çevre temizlik vergisi ve kullanım giderleri: Kiracıya aittir.\n• Yönetim gideri/aidat: olağan işletme giderleri Kiracıya; ana yapının büyük onarım, yenileme ve demirbaş nitelikli giderleri Kiraya Verene aittir.\n• Emlak vergisi: Kiralananın mülkiyetinden doğduğu için Kiraya Verene aittir.",
  "KİRALANANIN ZİYARET EDİLMESİ VE SATIŞI\nSözleşme süresinin son üç ayı içinde Kiracı, Kiralananı satın almak veya kiralamak isteyen adayların, önceden mutabık kalınan makul saatlerde Kiralananı gezip incelemesine izin verir. Kiralananın satılması hâlinde, TBK m. 351 saklı kalmak kaydıyla, yeni malik işbu sözleşmenin tarafı olur ve sözleşme hükümleriyle bağlıdır.",
  "SÖZLEŞMENİN SONA ERMESİ VE TAHLİYE\nSözleşme, aşağıdaki hâllerde süresinden önce sona erebilir: a) Ödeme temerrüdü: Kiracının kira bedelini ödemede temerrüde düşmesi hâlinde, Kiraya Veren TBK m. 315 uyarınca en az otuz günlük süre vererek borcun ifasını yazılı olarak ihtar edebilir; bu süre içinde ifa edilmezse sözleşmeyi feshedebilir. b) Kiraya Verenin ihtiyacı: Kiraya Veren, kendisinin, eşinin, alt/üst soyunun veya bakmakla yükümlü olduğu kişilerin işyeri ihtiyacı doğması hâlinde, TBK m. 350 uyarınca dava ile tahliye talep edebilir. c) Kiracının erken tahliyesi: Kiracı, süre bitiminden en az iki ay önce yazılı bildirim yapmaksızın erken tahliye ederse, Kiraya Verenin bundan doğan ve belgelendirilebilir gerçek zararını talep hakkı saklıdır. d) Tahliye taahhüdü: Taraflar arasında düzenlenmiş, geçerlilik şartlarını taşıyan yazılı bir tahliye taahhüdü varsa, TBK m. 352 hükümleri uygulanır.",
  "MÜCBİR SEBEP\nDeprem, sel, yangın, salgın hastalık, savaş, terör olayları, resmi makam kararları gibi tarafların makul kontrolü dışındaki öngörülemeyen hâller mücbir sebep sayılır. Mücbir sebep ifayı geçici olarak imkânsız veya aşırı güçleştirirse, ilgili Taraf durumu derhal diğer Tarafa yazılı bildirir ve yükümlülükler bu süre boyunca askıya alınır. Kiralananın bu süre zarfında kullanılamaması hâlinde kira bedelinde genel hükümlere göre uyarlama talep edilebilir. Mücbir sebebin otuz günden uzun sürmesi hâlinde Taraflardan her biri sözleşmeyi tazminatsız feshedebilir.",
  "KİŞİSEL VERİLERİN KORUNMASI\nTaraflar, işbu sözleşmenin kurulması ve ifası kapsamında elde ettikleri kişisel verileri, 6698 sayılı Kişisel Verilerin Korunması Kanunu ve ilgili mevzuata uygun olarak, yalnızca sözleşme amaçlarıyla sınırlı şekilde işleyeceğini ve üçüncü kişilerle ancak mevzuatın izin verdiği ölçüde paylaşacağını kabul ve taahhüt eder.",
  "TEBLİGAT\nTaraflar, işbu sözleşmenin 1. maddesinde belirtilen adreslerini tebligat adresi olarak kabul etmiştir. Adres değişiklikleri, noter kanalıyla, iadeli taahhütlü mektupla veya kayıtlı elektronik posta (KEP) yoluyla karşı tarafa bildirilmediği sürece, belirtilen adreslere yapılacak tebligatlar geçerli sayılır.",
  "[SON][KEFIL]KEFALET\nİşbu sözleşmede kefil gösterilmesi tarafların anlaşmasına bağlıdır. Kefil gösterilmesi hâlinde kefil; kefil olduğu azami tutarı, kefalet tarihini ve müteselsil kefil sıfatıyla yükümlülük altına girdiğini kendi el yazısıyla yazarak imzalar (TBK m. 583). Kefil evli ise kefaletin geçerliliği, eşin yazılı rızasının kefalet anında veya öncesinde alınmasına bağlıdır. Ancak kefil; ticaret siciline kayıtlı bir ticari işletmenin sahibi ya da bir ticaret şirketinin ortağı veya yöneticisi sıfatıyla ve işletme veya şirketle ilgili olarak kefil oluyorsa eşin rızası aranmaz (TBK m. 584/3).",
  "SÖZLEŞME EKLERİ\nAşağıdaki ekler işbu sözleşmenin ayrılmaz parçasıdır:\n• Ek-1: Teslim Tutanağı ve Demirbaş Listesi\n• Ek-2: Taraflara ait kimlik/imza belgesi örnekleri\n• Ek-3: Varsa güvence senedi / teminat mektubu\nEkler ile sözleşme metni arasında çelişki bulunması hâlinde, sözleşme metni esas alınır.",
  "[SON]UYUŞMAZLIKLARIN ÇÖZÜMÜ\nİşbu sözleşmeden ve kira ilişkisinden kaynaklanan uyuşmazlıklarda, dava açılmadan önce arabulucuya başvurulması dava şartıdır; ilamsız icra yoluyla yapılan tahliye takipleri bu kuralın dışındadır. Arabuluculuk faaliyeti sonunda anlaşmaya varılamaması hâlinde, uyuşmazlığın çözümünde {{mahkeme}} Mahkemeleri ve İcra Daireleri yetkilidir.",
  "[SON]DİĞER HÜKÜMLER\nSözleşmenin herhangi bir hükmünün geçersiz veya uygulanamaz olması, diğer hükümlerin geçerliliğini etkilemez. Taraflardan birinin sözleşmeden doğan bir hakkını kullanmaması, bu haktan feragat ettiği anlamına gelmez. İşbu sözleşmede hüküm bulunmayan hâllerde 6098 sayılı Türk Borçlar Kanunu ve ilgili diğer mevzuat hükümleri uygulanır. Sözleşmede yapılacak her türlü değişiklik, tarafların yazılı mutabakatı ile geçerlidir.",
  "[SON]YÜRÜRLÜK\nİşbu sözleşme, taraflarca okunmuş, anlaşılmış ve kabul edilerek iki asıl nüsha halinde düzenlenmiş olup, {{tarih}} tarihinde {{yer}}'da taraflarca imzalanarak yürürlüğe girmiştir.",
];

function wholeMoney(value: string) {
  const raw = value.trim();
  if (!raw) return "................................";
  const normalized = raw.includes(",") ? raw.replace(/\./g, "").replace(",", ".") : raw.replace(/\./g, "");
  const number = Math.round(Number(normalized) || 0);
  return `${new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 0 }).format(number)} ₺`;
}

export function rentalConditionTemplates(useType: OfflineRentalDetails["useType"]) {
  return useType === "commercial" ? COMMERCIAL : RESIDENTIAL;
}

/** Kullanıcının sağladığı şablonu seçilen tür ve sözleşme alanlarıyla doldurur. */
export function rentalContractConditions(details: OfflineRentalDetails, endDate: string) {
  const templates = rentalConditionTemplates(details.useType).filter((template) => !template.startsWith("[SON][KEFIL]") || details.hasGuarantor);
  const tokens: Record<string, string> = {
    kira: wholeMoney(details.monthlyRent), depozito: wholeMoney(details.deposit), odemeGun: details.paymentDay || "1", ilkVade: details.firstPaymentDueDate || "................................", sure: `${details.durationMonths || "12"} ay`, basla: details.startDate || "................................", bitis: endDate || "................................", iban: details.iban || "................................", kdv: details.kdvIncluded ? "KDV dâhil" : "KDV hariç", amac: details.usagePurpose || "................................", tapuNitelik: details.propertyType || "................................", mahkeme: details.courtCity || "Urla", tarih: details.startDate || "................................", yer: details.documentPlace || "Urla", maddeSayisi: String(templates.length), kisiSayisiCumle: details.residentsCount.trim() ? ` Kiralananda ${details.residentsCount.trim()} kişinin ikamet edeceği bildirilmiştir.` : "",
  };
  return templates.map((template) => template.replace(/^\[SON\]/, "").replace(/^\[KEFIL\]/, "").replace(/\{\{([^}]+)\}\}/g, (_, key: string) => tokens[key] ?? "................................"));
}
