import type { OfflineRentalDetails } from "./rentalContract";

export const RENTAL_CONDITIONS_TEMPLATE_VERSION = "global1881-rental-conditions-2026-08-v3-residential-commercial";

const RESIDENTIAL = [
  "Mecur, Kiracı'ya sağlam, tam ve kullanılmaya elverişli şekilde teslim edilmiştir. Demirbaşlar temiz, çalışır ve sağlam vaziyette teslim edilmiştir. Kiracı, teslim anında mecurda görünür bir ayıp bulunmadığını kabul ve beyan eder.",
  "Kiracı, Kiraya Verenin yazılı izni olmadan işbu Kira Sözleşmesinden doğan haklarının bir kısmını veyahut tamamını başkasına devir veya temlik edemeyeceği gibi; alt kiraya da veremez.",
  "Kiracı, mecuru mesken/konut olarak kullanacak olup, başka amaçlarla kullanamaz.",
  "Aylık kira bedeli net {{kira}}'dır. Kira bedelleri EFT ya da her türlü gönderme masrafları Kiracı'ya ait olmak üzere her ayın en geç {{odemeGun}}. günü Kiraya Veren'in yukarıda belirtilen banka hesabına Kiracı tarafından transfer edilecektir. Kira bedeli ve sair giderlerin zamanında ödenmemesi halinde 6098 sayılı Türk Borçlar Kanunu'nun ve 634 sayılı Kat Mülkiyeti Kanunu'nun ilgili hükümleri uygulanacaktır.",
  "Kiracının mecurda oturmaya devam ettiği hallerde, bir aylık kira bedelinin ödenmemesi halinde dönem sonuna kadar işleyecek kira bedellerinin tümü muacceliyet kazanır. Bunun için ihtarname keşidesine gerek yoktur. Ödenmeyen, eksik ödenen veya geç ödenen kira bedelleri için aylık %5 faiz uygulanır.",
  "Kiracının bir kira dönemi içinde iki ay kira bedelini ödememesi Kiraya Veren yönünden haklı tahliye sebebi olup, böyle bir durumda Kiracı, tüm borçlarını ödeyerek kiralananı tahliye edeceğini taahhüt eder.",
  "Kiracı depozito olarak {{depozito}} sözleşme tarihinde nakit olarak öder. Bu depozito bedeli; Kiracının kira borcu, aidat ve ortak gider borçlarının tamamının ödendiği ve mecurun hasarsız teslim edildiğinin tespitinin ardından Kiraya Veren tarafından 15 (on beş) gün içinde Kiracı'ya iade edilir. Tespit aşamasında herhangi bir borç veya hasar tespit edilirse depozito, öncelikle bu alacakların mahsubuna tahsis edilir; kalan tutar Kiracı'ya iade edilir.",
  "Kiracı, kullandığı doğalgaz, elektrik, su, kablolu TV, özel abonelikler, internet, telefon gibi hizmetlerin masraflarını ödeyecek olup; mecurun kullanımı ile ilgili ve mecurun kullanımı sırasında alınması gereken tüm abonelikler Kiracı adına alınacaktır.",
  "Kiraya Veren, Kiracının kusuru olmaksızın oluşan ana demirbaş ve tesisat hasarlarından sorumludur. Kiracı; küçük çaplı arızalar, kendi kusuru ve aşırı kullanımdan doğan zararlardan sorumlu olup olağan eskimeler bu kapsamın dışındadır. Kiracı, onarım gerektiren durumları derhal yazılı olarak Kiraya Veren'e bildirmekle yükümlüdür; bildirmediği için büyüyen zarardan sorumlu tutulur.",
  "Kiracı, kiralanan yerin içinde veya dışında kısmen veya tamamen tadilat veya tamirat yapabilmek için Kiraya Veren'den müsaade almalıdır.",
  "Kira süresi {{sure}} olup, sözleşmeyi sona erdirmek isteyen taraf, bitiş tarihinden en az 2 (iki) ay önce diğer tarafa yazılı bildirimde bulunmak zorundadır. Bu bildirimi yapmaksızın mecurdan ayrılan Kiracı, 2 (iki) aylık kira bedelini tazminat olarak öder. Taraflardan hiçbiri süresinde bildirim yapmazsa sözleşme, TÜİK tarafından açıklanan TÜFE on iki aylık ortalaması oranında kira artışı uygulanarak birer yıllık dönemlerle yenilenir.",
  "Kiracı, kira yılı dolmadan mecuru mahkemece kabul görmüş bir mücbir sebep olmaksızın tahliye ederse, kalan kira bedellerinin tamamı muaccel olmaz; 2 (iki) aylık kira bedeli ile bu süreye ait ortak gider ve aidatları tazminat olarak peşinen öder. Mecur bu süreden önce yeniden kiraya verilirse Kiracının sorumluluğu yeni kiranın başlangıç tarihinde sona erer. Kiraya Veren, mecuru en kısa sürede yeniden kiraya vermek için makul gayreti göstermekle yükümlüdür.",
  "Sözleşme herhangi bir sebeple sona erdiğinde Kiracı, sözleşme bitiş tarihinden itibaren 7 (yedi) gün içinde mecuru, teslim aldığı haliyle, demirbaşları ve eklentileriyle birlikte, kendi kusurundan ya da aşırı kullanımdan kaynaklanan yıpranmalar giderilerek temiz ve hazır şekilde Kiraya Veren'e teslim etmek zorundadır. Bu süre geçtikten sonra tahliye etmeyen Kiracı, fiilen çıktığı tarihe kadar aylık kira bedelini ve tüm giderleri ödemeye devam eder; Kiraya Veren'in ek zararları ayrıca talep hakkı saklıdır.",
  "Kira bedeli; her kira dönemi sonunda TÜİK tarafından açıklanan Yurt İçi Tüketici Fiyat Endeksindeki (TÜFE) on iki aylık ortalamalara göre değişim oranı üzerinden artırılacaktır. Verilerin geç açıklanması halinde önceki dönemlere göre oluşacak kira bedeli farkları da ilk dönem kira bedeline eklenerek ödenecektir.",
  "Kiralanan taşınmaza ilişkin giderler Kiracı'ya aittir. Kiracı, 6098 sayılı Türk Borçlar Kanunu ve 634 sayılı Kat Mülkiyeti Kanunu'nda düzenlenen hükümlere titizlikle uymak zorundadır. Kiracı, bu hükümlere uymadığı takdirde bu hususun sözleşmeye aykırılık ve tahliye nedeni olduğunu kabul ve beyan eder.",
  "Bu kira sözleşmesi uyarınca tarafların birbirlerine yapacakları her türlü ihbar veya talep yazılı olmalıdır. Kiracı ve Kiraya Veren tebligat adreslerindeki değişiklikleri bir ay içerisinde yazılı olarak diğer tarafa bildirmek zorundadır. Aksi takdirde sözleşmede yazılı adreslere yapılan tebligatlar geçerli sayılır.",
  "İşbu Kira Sözleşmesi'nin herhangi bir maddesinin herhangi bir sebeple geçersiz olduğuna hükmedilmesi halinde, sözleşmenin diğer hükümleri geçerliliğini koruyacaktır.",
  "İşbu Kira Sözleşmesi'nden kaynaklanan her türlü Damga Vergisi, stopaj ve sair masraflar Kiracı'nın sorumluluğundadır.",
  "Bu Kira Sözleşmesinden doğan uyuşmazlıklarda {{mahkeme}} Mahkemeleri ve İcra Daireleri yetkilidir.",
  "İşbu Kira Sözleşmesi'nde hüküm bulunmayan hallerde, 6098 sayılı Türk Borçlar Kanunu, 634 sayılı Kat Mülkiyeti Kanunu ve niteliğine uygun düştüğü sürece diğer yasal mevzuat hükümleri uygulanacaktır.",
  "Kiracı, kira süresinin son ayı içinde Kiraya Veren tarafından belirlenen makul gün ve saatlerde mecurun olası kiracılara gösterilmesine izin vermek zorundadır.",
  "İşbu kira sözleşmesi; 2 (iki) asıl nüsha ve {{maddeSayisi}} hususi şarttan ibaret olup, {{tarih}} tarihinde {{yer}}'da taraflarca imzalanarak yürürlüğe girmiştir.",
];

const COMMERCIAL = [
  "1. KİRA SÜRESİ VE YENİLEME\nKira süresi 1 (bir) yıl olup, künyede belirtilen tarihte başlar ve biter. Kiracı süre bitiminden en az on beş gün önce yazılı bildirimde bulunmazsa sözleşme aynı şartlarla bir yıl uzar; Kiracı sonraki her uzama yılının bitiminde de aynı bildirimle çıkabilir. Kiraya Veren, sürenin dolmasına dayanarak sözleşmeyi sona erdiremez; yasadan doğan tahliye davası hakları saklıdır.",
  "2. KİRA BEDELİ VE ÖDEME\nAylık net kira bedeli künyede belirtilen tutardır. Kiracı stopaj mükellefi ise brüt bedel üzerinden stopajı keserek beyan eder ve makbuz örneğini Kiraya Verene iletir. Kiraya Veren KDV mükellefi ise bedele KDV eklenir. Bedel Türk Lirası olarak kararlaştırılmıştır; döviz veya dövize endeksli belirleme yapılamaz.\nKıst dönem bedeli künyede belirtilen tarihte ödenir. Sonraki kiralar her ayın belirlenen gününde peşin olarak Kiraya Verenin künyede yazılı IBAN numaralı hesabına yatırılır. Geciken tutara yasal temerrüt faizi işler; fesih ve tahliye 14. maddeye tabidir.",
  "3. KİRA BEDELİNİN ARTIRILMASI\nKira bedeli her yenileme döneminde, bir önceki kira yılına ait TÜFE on iki aylık ortalama değişim oranında, ayrıca mutabakat aranmaksızın artar. Yürürlükte emredici bir üst sınır varsa artış bu sınırı aşamaz.\nBeş yıldan sonraki dönemlerde taraflar kira bedelinin yeniden belirlenmesini isteyebilir. Talep eden taraf, yeni dönemin başlangıcından en az otuz gün önce yazılı bildirimde bulunur veya dava açar. Yeni bedel belirlenene kadar mevcut kira ödenmeye devam eder, fark yasal faiziyle tahsil edilir.",
  "4. GÜVENCE BEDELİ (DEPOZİTO)\nKiracı, sözleşmeden doğabilecek borçlarına karşılık künyede belirtilen güvence bedelini öder; bu bedel üç aylık kirayı aşamaz. Güvence bedeli, Kiracının yazılı onayı olmadan çekilmemek üzere bankada müşterek imzalı vadeli hesapta tutulur; kira bedeline mahsup edilemez, nema Kiracıya aittir. Dekont bir ay içinde Kiracıya teslim edilir. Bedel, 5. maddedeki ilişik kesme belgelerinin tesliminden itibaren on beş gün içinde nemasıyla iade edilir; belgelendirilmiş hasar veya borç varsa mahsup edilerek bakiye ödenir.",
  "5. TESLİM, İADE VE İLİŞİK KESME\nKiralanan, Ek-1 Teslim Tutanağı ve Demirbaş Listesi'nde belirtilen durum ve donanımla, kullanıma elverişli ve ayıpsız olarak teslim edilir. Taraflar teslim anında durumu birlikte tespit eder ve anahtar adedini tutanağa yazar.\nKiracı, Kiralananı aldığı durumda geri verir; olağan kullanımdan doğan yıpranmadan sorumlu değildir. Kiraya Veren, geri alma sırasında tespit ettiği eksiklikleri en geç beş iş günü içinde yazılı bildirir; bildirmezse sorumluluk sona erer, gizli ayıplar bu kuralın dışındadır.\nKiracı tahliyede, yönetimden alınmış borcu yoktur yazısını, elektrik, su, doğalgaz ve internet aboneliklerine ilişkin kapama belgelerini ve anahtarları tam takım teslim eder. Abonelik borçları abone sıfatıyla Kiracıya aittir; bu belgeler güvence bedelinin iadesi için aranır.",
  "6. KULLANIM AMACI, RUHSAT VE TABELA\nKiralanan münhasıran künyede belirtilen faaliyet için kullanılır; amaç değişikliği Kiraya Verenin yazılı onayına tabidir, aksine kullanım akde aykırılıktır. Tapu niteliği ve iskân durumu imza öncesinde taraflarca kontrol edilmiştir; Kiraya Veren maliklik ve iskâna ilişkin belgeleri ibraz eder.\nİşyeri açma ve çalışma ruhsatı ile diğer izinler Kiracının sorumluluğunda ve masrafındadır. Kiracı, izinlerin alınabilirliğini imza öncesinde belediye nezdinde araştırdığını beyan eder; sonradan alınamaması hâlinde Kiraya Verenden tazminat isteyemez.\nKiracı, mevzuata ve yönetim planına uygun olmak kaydıyla cephede tabela bulundurabilir. Tabelanın imalatı, montajı, izinleri, elektriği ve bakımı Kiracıya aittir; tahliyede söker ve izleri onarır.",
  "7. DEVİR VE ALT KİRA\nKiracı, Kiraya Verenin yazılı onayı olmaksızın kira ilişkisini devredemez ve Kiralananı kısmen veya tamamen alt kiraya veremez. Kiraya Veren haklı sebep olmadıkça onaydan kaçınamaz; haksız ret hâlinde Kiracının tazminat hakkı saklıdır. Devir hâlinde devreden Kiracı iki yıl süreyle devralanla müteselsil sorumludur. Kiracı tüzel kişi ise, kontrolün el değiştirmesi sonucunu doğuran pay veya yönetim değişiklikleri on beş gün içinde Kiraya Verene yazılı bildirilir.",
  "8. KİRACININ YÜKÜMLÜLÜKLERİ\nKiracı; Kiralananı sözleşmeye ve kullanım amacına uygun, özenle kullanır. Olağan kullanımdan doğan küçük bakım ve onarımları (kapı-pencere donanımı, musluk, priz, ampul ve benzeri günlük kullanım unsurları) kendisi karşılar. Gidermekle yükümlü olmadığı ayıpları öğrenmesinden itibaren beş iş günü içinde yazılı bildirir. Elektrik, su, doğalgaz ve internet aboneliklerini kendi adına açtırır ve düzenli öder. Kiraya Verenin veya yetkilendirdiği kişilerin, makul süre önce haber vermek kaydıyla Kiralananı görmesine izin verir.",
  "9. KİRAYA VERENİN YÜKÜMLÜLÜKLERİ\nKiraya Veren; Kiralananın yapısal ve esaslı unsurlarına ilişkin, Kiracının kullanımından kaynaklanmayan bakım ve onarımları kendi giderleriyle ve gecikmeksizin yaptırır. Kiracının sözleşmeye uygun ve aralıksız kullanımını, haklı sebep ve önceden bildirim olmaksızın engellemez. Üçüncü kişilerin Kiralanan üzerinde Kiracının hakkıyla bağdaşmayan bir hak ileri sürmesi hâlinde, Kiracının bildirimi üzerine hukuki yollara başvurur ve Kiracının bu sebeple uğradığı zararı giderir.",
  "10. TADİLAT VE DEĞİŞİKLİKLER\nKiracı, tadilat, dekorasyon veya sabit tesisat değişikliğinden önce Kiraya Verenin yazılı onayını alır; onaylanan tadilatın masrafı aksi kararlaştırılmadıkça Kiracıya aittir. Binanın taşıyıcı sistemine (kolon, kiriş, perde duvar), ana sıhhi ve elektrik tesisatına müdahale hiçbir hâlde yapılamaz. Sözleşme sona erdiğinde, sökülmesi Kiralanana zarar verecek sabit tadilatlar aksi yazılı kararlaştırılmadıkça bedelsiz olarak Kiralanana kalır. Binanın yapısını bozmayan küçük onarımlar (kilit, reze, badana) bildirim gerektirmez ve bedeli Kiraya Verenden istenemez.",
  "11. KAT MÜLKİYETİ VE ORTAK ALANLAR\nKiralanan kat mülkiyetine tabi bir yapıda ise Kiracı, yönetim planı ile kat malikleri kurulu kararlarına uymakla yükümlüdür; yönetim planının bir örneği kendisine teslim edilmiştir. Ortak alanların ve varsa otoparkın kullanımı yönetim planı hükümlerine tabidir.",
  "12. VERGİ, GİDER VE SİGORTA\nKira stopajı, Kiracının mükellef olması hâlinde brüt bedel üzerinden kesilip beyan edilir. Çevre temizlik vergisi, abonelik ve kullanım giderleri Kiracıya aittir. Olağan yönetim ve işletme giderleri Kiracıya; ana yapının büyük onarım, yenileme ve demirbaş nitelikli giderleri ile emlak vergisi Kiraya Verene aittir. Damga vergisi doğması hâlinde Taraflarca eşit karşılanır.\nKiraya Veren, Zorunlu Deprem Sigortası ile bina sigortasını yaptırır ve kira süresince geçerli tutar. Kiracı, kendi demirbaş, emtia ve dekorasyonuna ilişkin sigortayı kendi maliyetiyle yaptırır ve poliçe örneğini bir ay içinde Kiraya Verene iletir.",
  "13. ZİYARET VE SATIŞ\nKiracı, sözleşmenin son üç ayında Kiralananı satın almak veya kiralamak isteyen adayların, önceden mutabık kalınan makul saatlerde Kiralananı gezip görmesine izin verir. Kiralananın satılması hâlinde yeni malik sözleşmenin tarafı olur ve hükümleriyle bağlıdır; yeni malikin yasadan doğan gereksinim sebebiyle tahliye hakkı saklıdır.",
  "14. SÖZLEŞMENİN SONA ERMESİ VE TAHLİYE\nSözleşme, süresinden önce aşağıdaki hâllerde sona erebilir:\na) Kiracının kira bedelini ödemede temerrüde düşmesi hâlinde Kiraya Veren, en az otuz günlük süre vererek borcun ifasını yazılı olarak ihtar eder; bu süre içinde ödenmezse sözleşmeyi feshedebilir.\nb) Kiracının bir kira yılı içinde iki haklı yazılı ihtara sebep olması hâlinde Kiraya Veren, kira yılının bitiminden itibaren bir ay içinde tahliye davası açabilir.\nc) Kiraya Verenin, kendisinin, eşinin, alt veya üst soyunun ya da bakmakla yükümlü olduğu kişilerin işyeri gereksinimi doğması hâlinde dava yoluyla tahliye talep edilebilir.\nd) Kiracının erken tahliyesi hâlinde Kiracı, Kiralananın benzer koşullarla yeniden kiralanabileceği makul süre boyunca kira bedelinden sorumludur. Kiraya Veren, Kiralananın yeniden kiralanması için makul çabayı gösterir; yaptığı tasarruflar ve elde ettiği yeni kira geliri bu tutardan indirilir.\ne) Geçerlilik şartlarını taşıyan yazılı bir tahliye taahhüdü varsa, taahhüt edilen tarihte tahliye edilmemesi hâlinde Kiraya Veren bir ay içinde icra veya dava yoluna başvurabilir.",
  "15. MÜCBİR SEBEP\nDeprem, sel, yangın, salgın hastalık, savaş, terör olayları ve resmî makam kararları gibi Tarafların makul kontrolü dışındaki öngörülemeyen hâller mücbir sebep sayılır. Mücbir sebep ifayı geçici olarak imkânsız veya aşırı güç kılarsa, etkilenen Taraf durumu derhal yazılı bildirir ve yükümlülükler bu süre boyunca askıya alınır. Kiralananın bu süre zarfında kullanılamaması hâlinde kira bedelinde uyarlama talep edilebilir. Mücbir sebebin doksan günden uzun sürmesi hâlinde Taraflardan her biri sözleşmeyi tazminatsız feshedebilir.",
  "16. KİŞİSEL VERİLERİN KORUNMASI\nTaraflar, sözleşme kapsamında elde ettikleri kişisel verileri 6698 sayılı Kanun'a uygun olarak, yalnızca sözleşme amaçlarıyla sınırlı biçimde işleyeceğini ve üçüncü kişilerle ancak mevzuatın izin verdiği ölçüde paylaşacağını kabul eder.",
  "17. TEBLİGAT\nTaraflar, künyede belirtilen adreslerini tebligat adresi olarak kabul etmiştir. Adres değişiklikleri noter, iadeli taahhütlü mektup veya KEP yoluyla karşı tarafa bildirilmediği sürece, künyedeki adreslere yapılan tebligatlar geçerli sayılır.",
  "18. EKLER\nEk-1 Teslim Tutanağı ve Demirbaş Listesi, Ek-2 kimlik ve imza belgesi örnekleri, Ek-3 varsa güvence senedi veya teminat mektubu işbu sözleşmenin ayrılmaz parçasıdır. Ekler ile sözleşme metni arasında çelişki hâlinde sözleşme metni esas alınır; Ek-1'de yer alan durum tespitleri bu kuralın dışındadır.",
  "19. UYUŞMAZLIKLARIN ÇÖZÜMÜ\nBu sözleşmeden doğan uyuşmazlıklarda dava açılmadan önce arabulucuya başvurulması dava şartıdır; ilamsız icra yoluyla yapılan tahliye takipleri bu kuralın dışındadır. Anlaşma sağlanamaması hâlinde künyede belirtilen yer Mahkemeleri ve İcra Daireleri yetkilidir.",
  "20. DİĞER HÜKÜMLER\nBir hükmün geçersizliği diğer hükümleri etkilemez. Bir hakkın kullanılmaması ondan feragat sayılmaz. Hüküm bulunmayan hâllerde 6098 sayılı Türk Borçlar Kanunu ve ilgili mevzuat uygulanır. Değişiklikler yalnızca Tarafların yazılı mutabakatıyla geçerlidir.",
  "21. YÜRÜRLÜK\nİşbu sözleşme, Taraflarca okunmuş, anlaşılmış ve kabul edilerek iki asıl nüsha hâlinde düzenlenmiş olup, künyede belirtilen yer ve tarihte imzalanarak yürürlüğe girmiştir.",
];

function wholeMoney(value: string) {
  const raw = value.trim();
  if (!raw) return "................................";
  const normalized = raw.includes(",") ? raw.replace(/\./g, "").replace(",", ".") : raw.replace(/\./g, "");
  const number = Math.round(Number(normalized) || 0);
  return `${new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 0 }).format(number)} ₺`;
}

export function rentalConditionTemplates(useType: OfflineRentalDetails["useType"]) {
  return useType === "commercial" ? COMMERCIAL : RESIDENTIAL;
}

/** Kullanıcının sağladığı şablonu seçilen tür ve sözleşme alanlarıyla doldurur. */
export function rentalContractConditions(details: OfflineRentalDetails, endDate: string) {
  const templates = rentalConditionTemplates(details.useType).filter((template) => !template.startsWith("[SON][KEFIL]") || details.hasGuarantor);
  const tokens: Record<string, string> = {
    kira: wholeMoney(details.monthlyRent), depozito: wholeMoney(details.deposit), odemeGun: details.paymentDay || "1", ilkVade: details.firstPaymentDueDate || "................................", sure: `${details.durationMonths || "12"} ay`, basla: details.startDate || "................................", bitis: endDate || "................................", iban: details.iban || "................................", kdv: details.kdvIncluded ? "KDV dâhil" : "KDV hariç", amac: details.usagePurpose || "................................", tapuNitelik: details.propertyType || "................................", mahkeme: details.courtCity || "Urla", tarih: details.startDate || "................................", yer: details.documentPlace || "Urla", maddeSayisi: String(templates.length), kisiSayisiCumle: details.residentsCount.trim() ? ` Kiralananda ${details.residentsCount.trim()} kişinin ikamet edeceği bildirilmiştir.` : "",
  };
  return templates.map((template) => template.replace(/^\[SON\]/, "").replace(/^\[KEFIL\]/, "").replace(/\{\{([^}]+)\}\}/g, (_, key: string) => tokens[key] ?? "................................"));
}
