CREATE TABLE `activeRentalSummaries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`tenantName` varchar(180) NOT NULL,
	`tenantPhone` varchar(40) NOT NULL,
	`contractDate` timestamp NOT NULL,
	`rentIncreaseDate` timestamp,
	`evictionDate` timestamp,
	`monthlyRent` decimal(14,2) NOT NULL,
	`neighborhood` varchar(120) NOT NULL,
	`assignedUserId` int NOT NULL,
	`importFingerprint` varchar(64) NOT NULL,
	`importedByUserId` int NOT NULL,
	`increaseRate` decimal(7,4),
	`increaseRateSource` varchar(180),
	`increaseRatePeriod` varchar(20),
	`increaseRateEntryMethod` enum('official_reference','manual') NOT NULL DEFAULT 'manual',
	`increaseRateEnteredByUserId` int,
	`increaseRateEnteredAt` timestamp,
	`noticeStatus` enum('notPrepared','prepared','reviewed','shared') NOT NULL DEFAULT 'notPrepared',
	`noticePreparedAt` timestamp,
	`noticeReviewedByUserId` int,
	`noticeReviewedAt` timestamp,
	`noticeSharedByUserId` int,
	`noticeSharedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `activeRentalSummaries_id` PRIMARY KEY(`id`),
	CONSTRAINT `activeRentalSummaries_importFingerprint_unique` UNIQUE(`importFingerprint`)
);
