import { useEffect, useMemo, useState } from "react";
import { BellRing, LockKeyhole, RefreshCw, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/_core/hooks/useAuth";
import { findCustomerRequestMatches, parseCustomerRequest } from "@/lib/customerRequests";
import { listOfflineRecords, type OfflineRecord } from "@/lib/offlineStore";

export default function BrokerRequestMatches() {
  const { user } = useAuth(); const [records, setRecords] = useState<OfflineRecord[]>([]); const [updatedAt, setUpdatedAt] = useState(""); const refresh = async () => { setRecords(await listOfflineRecords()); setUpdatedAt(new Date().toLocaleString("tr-TR")); }; useEffect(() => { void refresh(); }, []); const matches = useMemo(() => findCustomerRequestMatches(records), [records]); const requestCount = records.filter((record) => Boolean(parseCustomerRequest(record))).length;
  if (user?.role !== "admin") return <div className="min-h-screen bg-[#f7f7f4] px-6 py-12"><Card className="mx-auto max-w-xl rounded-2xl border-[#ead6c9] bg-[#fff8f6]"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-2xl text-[#8d4537]"><LockKeyhole className="h-6 w-6" /> Manager yetkisi gerekli</CardTitle></CardHeader><CardContent><p className="text-sm text-[#70807c]">Ofis içi talep-portföy eşleşmeleri yalnız broker manager tarafından görülür. Danışmanlar kendi taleplerini Müşteri Talepleri ekranından takip eder.</p></CardContent></Card></div>;
  return <div className="min-h-screen bg-[#f7f7f4] px-5 py-7 md:px-10 md:py-9"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.22em] text-[#a17b43]"><BellRing className="h-3.5 w-3.5" /> Broker eşleşme bildirimi</p><h1 className="font-serif text-4xl tracking-[-0.04em] text-[#223230]">Talep ve Portföy Eşleşmeleri</h1><p className="mt-2 max-w-3xl text-sm text-[#70807c]">Açık müşteri talepleri, sözleşme/portföy kayıtlarıyla konum, bütçe, işlem türü ve nitelik açısından eşleştirilir. Müşteri kişisel verileri bu bildirime dahil değildir.</p></div><Button variant="outline" className="rounded-xl bg-white" onClick={() => void refresh()}><RefreshCw className="mr-2 h-4 w-4" /> Yenile</Button></header><div className="mb-5 grid gap-4 sm:grid-cols-2"><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-[#718079]">Ofis havuzundaki talep</p><p className="mt-2 font-serif text-3xl text-[#173e39]">{requestCount}</p></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-[#718079]">İncelenecek olası eşleşme</p><p className="mt-2 font-serif text-3xl text-[#173e39]">{matches.length}</p></CardContent></Card></div><Card className="rounded-2xl border-[#e5e8e3] bg-white"><CardHeader><CardTitle className="font-serif text-xl">Broker inceleme listesi</CardTitle><p className="text-xs text-[#87938f]">Son yenileme: {updatedAt || "yükleniyor"}. Bu liste yönlendirme amacı taşır; broker onayı olmadan danışmanlar arası müşteri verisi paylaşımı yapılmaz.</p></CardHeader><CardContent><div className="space-y-3">{matches.map((match) => <div key={`${match.requestRecordId}-${match.candidateRecordId}`} className="rounded-xl border border-[#eadfca] bg-[#fffdf8] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium text-[#34433f]">{match.operation === "sale" ? "Satılık" : "Kiralık"} talep ↔ {match.propertyType || "Portföy"}</p><p className="mt-1 text-sm text-[#55635e]">{match.location} · {match.price ? `${match.price.toLocaleString("tr-TR")} ₺` : "Bedel kayıtlı değil"}</p><p className="mt-2 text-xs text-[#8d6f3f]">Talep sahibi danışman: <strong>{match.requesterName || match.requesterUserId}</strong> · Portföy danışmanı: <strong>{match.portfolioAdvisorUserId}</strong> · {match.reasons.join(" · ")}</p></div><span className="rounded-full bg-[#f5ead1] px-2 py-1 text-[10px] font-semibold text-[#8d6f3f]">Broker incelemesi</span></div></div>)}{!matches.length && <div className="rounded-xl bg-[#f7f7f4] px-4 py-12 text-center text-sm text-[#87938f]"><ShieldCheck className="mx-auto mb-3 h-6 w-6 text-[#a17b43]" />Şu anda koşulları karşılayan çapraz danışman eşleşmesi bulunmuyor. Yedekler birleştirildikçe havuz tekrar taranır.</div>}</div></CardContent></Card></div>;
}
