import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileSignature, Printer, Plus, RefreshCw } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { rental: "Kira", sale: "Satış", authority: "Yetki" };
const statusLabels: Record<string, string> = { draft: "Taslak", review: "İncelemede", approved: "Onaylandı", signed: "İmzalandı", active: "Aktif", completed: "Tamamlandı", cancelled: "İptal" };

export default function Contracts() {
  const contracts = trpc.contracts.list.useQuery();
  const utils = trpc.useUtils();
  const create = trpc.contracts.create.useMutation({ onSuccess: () => utils.contracts.list.invalidate() });
  const transition = trpc.contracts.transition.useMutation({ onSuccess: () => utils.contracts.list.invalidate() });
  const [type, setType] = useState<"rental" | "sale" | "authority">("rental");
  const [title, setTitle] = useState("");
  const [contractNo, setContractNo] = useState("");
  const [amount, setAmount] = useState("");

  const submit = () => { if (!title || !contractNo) return; create.mutate({ type, title, contractNo, amount: amount || undefined }); setTitle(""); setContractNo(""); setAmount(""); };
  return <div className="min-h-screen bg-[#f7f7f4] px-5 py-7 md:px-10 md:py-9"><header className="mb-7 flex items-end justify-between"><div><img src="/manus-storage/01_logo_yatay_6b31c4b8.webp" alt="Global 1881 Gayrimenkul" className="mb-5 h-12 w-auto max-w-[270px] object-contain object-left" /><p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.22em] text-[#a17b43]">Belge çalışma alanı</p><h1 className="font-serif text-4xl tracking-[-0.04em] text-[#223230]">Sözleşmeler</h1><p className="mt-2 text-sm text-[#70807c]">Örnek paketteki kira, satış ve yetki akışlarını merkezi kayıt düzenine taşıyın.</p><img src="/manus-storage/21_muhur_seffaf_9a34c4d4.png" alt="Global 1881 mühür" className="hidden print:block print:absolute print:right-10 print:top-10 print:h-24 print:w-24 print:object-contain" /></div><Button onClick={() => window.print()} variant="outline" className="rounded-xl bg-white"><Printer className="mr-2 h-4 w-4" /> Yazdır</Button></header>
    <div className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Card className="rounded-2xl border-[#e5e8e3] bg-white/80"><CardHeader><CardTitle className="font-serif text-xl">Yeni sözleşme</CardTitle><p className="text-xs text-[#87938f]">Kayıt ilk olarak taslak oluşturulur.</p></CardHeader><CardContent className="space-y-4"><div><label className="mb-1.5 block text-xs font-semibold text-[#56635f]">Sözleşme türü</label><Select value={type} onValueChange={(v) => setType(v as typeof type)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="rental">Kira sözleşmesi</SelectItem><SelectItem value="sale">Satış sözleşmesi</SelectItem><SelectItem value="authority">Yetki sözleşmesi</SelectItem></SelectContent></Select></div><div><label className="mb-1.5 block text-xs font-semibold text-[#56635f]">Kayıt numarası</label><Input value={contractNo} onChange={(e) => setContractNo(e.target.value)} placeholder="KRS-2026-001" /></div><div><label className="mb-1.5 block text-xs font-semibold text-[#56635f]">Başlık</label><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Taşınmaz / taraf özeti" /></div><div><label className="mb-1.5 block text-xs font-semibold text-[#56635f]">Bedel (₺)</label><Input value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="decimal" placeholder="450000" /></div><Button onClick={submit} disabled={create.isPending || !title || !contractNo} className="w-full rounded-xl bg-[#173e39] hover:bg-[#20554e]"><Plus className="mr-2 h-4 w-4" /> {create.isPending ? "Kaydediliyor…" : "Taslak oluştur"}</Button>{create.isError && <p role="alert" className="text-xs text-[#a85745]">Kayıt oluşturulamadı. Numaranın benzersiz olduğundan emin olun.</p>}</CardContent></Card>
      <Card className="rounded-2xl border-[#e5e8e3] bg-white/80"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="font-serif text-xl">Kayıtlar</CardTitle><p className="text-xs text-[#87938f]">Rolünüze göre görünür sözleşmeler</p></div><Button variant="ghost" size="icon" onClick={() => contracts.refetch()} aria-label="Sözleşmeleri yenile"><RefreshCw className="h-4 w-4" /></Button></CardHeader><CardContent>{contracts.isLoading ? <p role="status" className="py-10 text-center text-sm text-[#87938f]">Sözleşmeler yükleniyor…</p> : contracts.isError ? <p role="alert" className="py-10 text-center text-sm text-[#a85745]">Sözleşmeler alınamadı.</p> : !contracts.data?.length ? <div className="rounded-xl bg-[#f7f7f4] px-4 py-10 text-center text-sm text-[#87938f]"><FileSignature className="mx-auto mb-3 h-6 w-6 text-[#bd975d]" />Henüz sözleşme kaydı yok.</div> : <div className="space-y-2">{contracts.data.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-[#edf0ec] p-4"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#e8dfcc] text-[#8d6f3f]"><FileSignature className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#34433f]">{item.title}</p><p className="mt-1 text-[10px] text-[#87938f]">{item.contractNo} · {labels[item.type]}</p></div><span className="rounded-full bg-[#eef1ed] px-2.5 py-1 text-[10px] font-semibold text-[#60706b]">{statusLabels[item.status]}</span>{item.status === "draft" && <Button size="sm" variant="outline" onClick={() => transition.mutate({ id: item.id, status: "review" })}>İncelemeye gönder</Button>}</div>)}</div>}</CardContent></Card></div></div>;
}
