import { useEffect, useMemo, useState } from "react";
import { FileText, ReceiptText, RefreshCw, Save, Target, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { formatAuthorityCurrency, formatWholeCurrencyInput } from "@/lib/authorityContract";
import { ANNUAL_TARGET_SCHEMA, calculateAnnualTargetProgress, parseAnnualTarget } from "@/lib/annualTargets";
import { getUserId, listOfflineRecords, saveOfflineRecord, type OfflineRecord } from "@/lib/offlineStore";
import { formatTurkishDate, formatTurkishDateTime } from "@/lib/turkishDate";

type PersonalContract = { id: string; title: string; type: "Satış / Yetki" | "Kira"; contractNo: string; date: string; amount?: string; status: string };
function parseContract(record: OfflineRecord): PersonalContract | null { if (record.entity !== "contract") return null; try { const snapshot = JSON.parse(record.details) as { schema?: string; contractNo?: string; contractDate?: string; startDate?: string; price?: string; monthlyRent?: string }; if (snapshot.schema?.startsWith("global1881-offline-authority")) return { id: record.id, title: record.title, type: "Satış / Yetki", contractNo: snapshot.contractNo ?? "—", date: snapshot.contractDate ?? record.updatedAt.slice(0, 10), amount: snapshot.price, status: record.status }; if (snapshot.schema?.startsWith("global1881-offline-rental")) return { id: record.id, title: record.title, type: "Kira", contractNo: snapshot.contractNo ?? "—", date: snapshot.startDate ?? record.updatedAt.slice(0, 10), amount: snapshot.monthlyRent, status: record.status }; } catch { /* bozuk kayıt kişisel listeyi engellemez */ } return null; }
const amountInputToNumber = (value: string) => Number(value.replace(/[^0-9]/g, "")) || 0;

export default function MyOfflineContracts() {
  const [records, setRecords] = useState<OfflineRecord[]>([]); const [updatedAt, setUpdatedAt] = useState(""); const [year, setYear] = useState(() => String(new Date().getFullYear())); const [targetAmount, setTargetAmount] = useState(""); const [message, setMessage] = useState("");
  const userId = getUserId(); const refresh = async () => { setRecords(await listOfflineRecords()); setUpdatedAt(formatTurkishDateTime(new Date())); }; useEffect(() => { void refresh(); }, []);
  const ownRecords = useMemo(() => records.filter((record) => record.userId === userId), [records, userId]); const contracts = useMemo(() => ownRecords.map(parseContract).filter((item): item is PersonalContract => Boolean(item)).sort((a, b) => b.date.localeCompare(a.date)), [ownRecords]); const sales = contracts.filter((item) => item.type === "Satış / Yetki").length; const rentals = contracts.filter((item) => item.type === "Kira").length; const plannedCollections = ownRecords.filter((record) => record.entity === "obligation" && record.status === "planned").length; const targetProgress = useMemo(() => userId ? calculateAnnualTargetProgress(records, userId, year) : null, [records, userId, year]); const progressWidth = Math.min(Math.max(targetProgress?.progressPercent ?? 0, 0), 100);
  const saveTarget = async () => { const amount = amountInputToNumber(targetAmount); if (!userId) { setMessage("Önce Yerel Çalışma Alanı’ndan offline kullanıcı kodunuzu kaydedin."); return; } if (!/^\d{4}$/.test(year) || amount <= 0) { setMessage("Geçerli bir yıl ve sıfırdan büyük, kuruşsuz ciro hedefi girin."); return; } const latest = records.flatMap((record) => { const target = parseAnnualTarget(record); return target && record.userId === userId && target.year === year ? [record] : []; }).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0]; await saveOfflineRecord({ entity: "target", title: `${year} hizmet bedeli ciro hedefi — ${userId}`, details: JSON.stringify({ schema: ANNUAL_TARGET_SCHEMA, year, targetAmount: amount, currency: "TRY", previousTargetRecordId: latest?.id }), amount: String(amount), status: "active" }); setTargetAmount(""); setMessage(`${year} yılı hedefiniz kaydedildi. Önceki hedef varsa yeni sürüm ayrı kayıt olarak izlenir.`); await refresh(); };
  return <div className="min-h-screen bg-[#f7f7f4] px-5 py-7 md:px-10 md:py-9"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.22em] text-[#a17b43]"><UserRound className="h-3.5 w-3.5" /> Kişisel offline görünüm</p><h1 className="font-serif text-4xl tracking-[-0.04em] text-[#223230]">Benim Sözleşmelerim</h1><p className="mt-2 max-w-3xl text-sm text-[#70807c]">Yalnızca aktif offline kullanıcı kodu <strong>{userId || "belirtilmemiş"}</strong> ile oluşturulan kayıtlar görünür. Bu ekranda başka danışman verisi veya sıralama yer almaz.</p></div><Button variant="outline" onClick={() => void refresh()} className="rounded-xl bg-white"><RefreshCw className="mr-2 h-4 w-4" /> Yenile</Button></header>
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Benim toplam sözleşmem</p><p className="mt-2 font-serif text-3xl text-[#173e39]">{contracts.length}</p></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Satış / yetki · kira</p><p className="mt-2 font-serif text-3xl text-[#173e39]">{sales} <span className="text-lg text-[#718079]">/</span> {rentals}</p></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Planlı kira vadesi</p><p className="mt-2 font-serif text-3xl text-[#173e39]">{plannedCollections}</p></CardContent></Card></div>
    <Card className="mb-6 rounded-2xl border-[#dbe5dd] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-xl"><Target className="h-5 w-5 text-[#a17b43]" /> Yıllık hizmet bedeli ciro hedefim</CardTitle><p className="text-xs text-[#87938f]">Hedef, KDV hariç hizmet bedeli cirosu içindir. Güncelleme yaptığınızda önceki hedef silinmez; yeni sürüm olarak şifreli yedek/merge akışına dahil olur.</p></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-[150px_1fr_auto]"><div><label className="mb-1.5 block text-xs font-semibold text-[#56635f]">Yıl</label><Input inputMode="numeric" maxLength={4} value={year} onChange={(event) => setYear(event.target.value.replace(/\D/g, "").slice(0, 4))} /></div><div><label className="mb-1.5 block text-xs font-semibold text-[#56635f]">Ciro hedefi (₺, KDV hariç)</label><Input inputMode="numeric" value={targetAmount} onChange={(event) => setTargetAmount(formatWholeCurrencyInput(event.target.value))} placeholder="Örn. 1.200.000" /></div><Button onClick={() => void saveTarget()} className="self-end bg-[#173e39] text-white hover:bg-[#20554e] hover:text-white"><Save className="mr-2 h-4 w-4" /> Hedefi kaydet</Button></div>{targetProgress ? <div className="rounded-xl bg-[#f5f8f5] p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs text-[#718079]">{targetProgress.year} hedefi</p><p className="mt-1 font-serif text-2xl text-[#173e39]">{formatAuthorityCurrency(targetProgress.targetAmount, "TRY")}</p></div><div className="text-right"><p className="text-xs text-[#718079]">Gerçekleşen hizmet bedeli cirosu</p><p className="mt-1 font-serif text-2xl text-[#173e39]">{formatAuthorityCurrency(targetProgress.actualAmount, "TRY")}</p></div></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-[#dce8df]"><div className="h-full rounded-full bg-[#2b786e]" style={{ width: `${progressWidth}%` }} /></div><div className="mt-2 flex flex-wrap justify-between gap-2 text-xs text-[#4f615c]"><span>İlerleme: <strong>%{targetProgress.progressPercent}</strong></span><span>{targetProgress.remainingAmount >= 0 ? `Kalan: ${formatAuthorityCurrency(targetProgress.remainingAmount, "TRY")}` : `Hedef üstü: ${formatAuthorityCurrency(Math.abs(targetProgress.remainingAmount), "TRY")}`}</span><span>{targetProgress.revisionCount} hedef sürümü</span></div></div> : <p className="rounded-lg bg-[#fffaf0] px-3 py-2 text-xs text-[#8d6f3f]">{year} yılı için hedef henüz kaydedilmedi.</p>}{message && <p role="status" className="rounded-lg bg-[#f5fbf8] px-3 py-2 text-xs text-[#2b786e]">{message}</p>}</CardContent></Card>
    <Card className="rounded-2xl border-[#e5e8e3] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-xl"><FileText className="h-5 w-5 text-[#a17b43]" /> Kişisel sözleşme listesi</CardTitle><p className="text-xs text-[#87938f]">Son yenileme: {updatedAt || "yükleniyor"}. Bu liste yalnızca kişisel takip içindir; değerlendirme veya sıralama yapılmaz.</p></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="border-b text-left text-xs uppercase tracking-wide text-[#718079]"><tr><th className="px-3 py-3">Kayıt no</th><th className="px-3 py-3">Sözleşme</th><th className="px-3 py-3">Tür</th><th className="px-3 py-3">Tarih</th><th className="px-3 py-3">Tutar</th><th className="px-3 py-3">Durum</th></tr></thead><tbody>{contracts.map((contract) => <tr key={contract.id} className="border-b border-[#edf0ec]"><td className="px-3 py-4 font-mono text-xs text-[#173e39]">{contract.contractNo}</td><td className="px-3 py-4 font-medium text-[#34433f]">{contract.title}</td><td className="px-3 py-4">{contract.type}</td><td className="px-3 py-4">{formatTurkishDate(contract.date)}</td><td className="px-3 py-4">{contract.amount ? `${contract.amount} ₺` : "—"}</td><td className="px-3 py-4">{contract.status}</td></tr>)}</tbody></table></div>{!userId && <p className="mt-4 rounded-lg bg-[#fff2f0] px-3 py-2 text-xs text-[#a13f36]">Bu ekranı kullanmak için önce Yerel Çalışma Alanı’ndan offline kullanıcı kodunuzu kaydedin.</p>}{userId && !contracts.length && <p className="py-10 text-center text-sm text-[#718079]">Bu kullanıcı koduna ait sözleşme kaydı bulunmuyor.</p>}</CardContent></Card><Card className="mt-6 rounded-2xl border-[#eadfca] bg-[#fffaf0]"><CardContent className="flex gap-3 p-4 text-xs text-[#7d6439]"><ReceiptText className="mt-0.5 h-4 w-4 shrink-0" /><p>Ofis geneli KDV ve hizmet bedeli toplamları için <strong>Sözleşme ve Finansal İstatistikler</strong> menüsünü kullanın. Bu kişisel ekran, yalnızca kendi oluşturduğunuz kayıtları ve hedefinizi takip etmeniz için ayrıdır.</p></CardContent></Card></div>;
}
