import { useEffect, useMemo, useState } from "react";
import { AlertCircle, BarChart3, FileText, Printer, ReceiptText, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { buildAuthorityPerformance, buildYearlyVatCollectionSummary, sumAuthorityPerformance } from "@/lib/authorityPerformance";
import { formatAuthorityCurrency } from "@/lib/authorityContract";
import { listOfflineRecords, type OfflineRecord } from "@/lib/offlineStore";
import { formatTurkishDateTime } from "@/lib/turkishDate";

function CurrencyAmounts({ values, emphasis = false }: { values: Record<string, number>; emphasis?: boolean }) {
  const entries = Object.entries(values).filter(([, amount]) => amount > 0);
  return entries.length ? <div className="space-y-1">{entries.map(([currency, amount]) => <p key={currency} className={`whitespace-nowrap ${emphasis ? "font-semibold text-[#a85745]" : ""}`}>{formatAuthorityCurrency(amount, currency as "TRY" | "USD" | "EUR")}</p>)}</div> : <span className="text-muted-foreground">—</span>;
}

export default function OfflineConsultantPerformance() {
  const [records, setRecords] = useState<OfflineRecord[]>([]);
  const [updatedAt, setUpdatedAt] = useState("");
  const refresh = async () => { setRecords(await listOfflineRecords()); setUpdatedAt(formatTurkishDateTime(new Date())); };
  useEffect(() => { void refresh(); }, []);
  const rows = useMemo(() => buildAuthorityPerformance(records), [records]);
  const totals = useMemo(() => sumAuthorityPerformance(rows), [rows]);
  const yearlyRows = useMemo(() => buildYearlyVatCollectionSummary(records), [records]);

  return <div className="authority-print-shell min-h-screen bg-[#f7f7f4] px-5 py-7 md:px-10 md:py-9"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.22em] text-[#a17b43]"><BarChart3 className="h-3.5 w-3.5" /> Offline sözleşme istatistikleri</p><h1 className="font-serif text-4xl tracking-[-0.04em] text-[#223230]">Sözleşme ve Finansal İstatistikler</h1><p className="mt-2 max-w-3xl text-sm text-[#70807c]">Yerel cihazdaki ve manager tarafından birleştirilmiş sözleşme kayıtlarının toplu mali görünümüdür. Bu ekranda kişisel puan, başarı sıralaması veya danışman karşılaştırması gösterilmez.</p></div><div className="print:hidden flex gap-2"><Button variant="outline" onClick={() => void refresh()} className="rounded-xl bg-white"><RefreshCw className="mr-2 h-4 w-4" /> Yenile</Button><Button variant="outline" onClick={() => window.print()} className="rounded-xl bg-white"><Printer className="mr-2 h-4 w-4" /> A4 yazdır</Button></div></header>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Toplam sözleşme kaydı</p><p className="mt-2 font-serif text-3xl text-[#173e39]">{totals.contractCount}</p></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Hizmet bedeli (KDV hariç)</p><div className="mt-2 font-serif text-xl text-[#173e39]"><CurrencyAmounts values={totals.serviceFeeByCurrency} /></div></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Faturalı KDV toplamı (%20)</p><div className="mt-2 font-serif text-xl text-[#173e39]"><CurrencyAmounts values={totals.expectedVatByCurrency} /></div></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Net hizmet geliri</p><div className="mt-2 font-serif text-xl text-[#173e39]"><CurrencyAmounts values={totals.netServiceIncomeByCurrency} /></div></CardContent></Card><Card className="rounded-2xl border-[#ecd9d4] bg-[#fff9f7]"><CardContent className="p-5"><p className="text-xs text-[#a85745]">KDV içeride kaldığı için tahmini kayıp</p><div className="mt-2 font-serif text-xl"><CurrencyAmounts values={totals.absorbedVatLossByCurrency} emphasis /></div></CardContent></Card></div>
    <div className="mb-6 grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><Card className="rounded-2xl border-[#e5e8e3] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-xl"><FileText className="h-5 w-5 text-[#a17b43]" /> Sözleşme türü dağılımı</CardTitle><p className="text-xs text-[#87938f]">Kayıtlar yalnız türlerine göre toplulaştırılır.</p></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-xl bg-[#f5f8f5] p-4"><p className="text-xs text-[#718079]">Satış sözleşmesi</p><p className="mt-1 font-serif text-3xl text-[#173e39]">{totals.saleContractCount}</p></div><div className="rounded-xl bg-[#f5f8f5] p-4"><p className="text-xs text-[#718079]">Kira sözleşmesi</p><p className="mt-1 font-serif text-3xl text-[#173e39]">{totals.rentalContractCount}</p></div></CardContent></Card><Card className="rounded-2xl border-[#eadfca] bg-[#fffaf0]"><CardContent className="flex gap-3 p-5 text-xs text-[#7d6439]"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0" /><p><strong>Yönetim göstergesi:</strong> Satışta hizmet bedeli, sözleşmedeki tutar veya girilen oranla; kiralamada ise bir aylık kira ile hesaplanır. KDV ayrıca tahsil edilmediyse ve alınan tutar KDV dâhil faturaya dönüştürülürse, içerde kalan KDV net gelirden ayrıştırılarak tahmini kayıp olarak gösterilir. Bu rapor fatura/beyanname yerine geçmez; mali müşavirinizle teyit edin.</p></CardContent></Card></div>
    <Card className="rounded-2xl border-[#e5e8e3] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-xl"><ReceiptText className="h-5 w-5 text-[#a17b43]" /> Yıllık KDV tahsilat ve mali özet</CardTitle><p className="text-xs text-[#87938f]">Son yenileme: {updatedAt || "yükleniyor"}. Yıl bazında toplam sözleşme, KDV ve tahmini kayıp görünümü sunulur.</p></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="border-b text-left text-xs uppercase tracking-wide text-[#718079]"><tr><th className="px-3 py-3">Yıl</th><th className="px-3 py-3 text-right">Sözleşme</th><th className="px-3 py-3">Faturalı KDV</th><th className="px-3 py-3">Net hizmet geliri</th><th className="px-3 py-3 text-[#a85745]">Tahmini yıllık kayıp</th></tr></thead><tbody>{yearlyRows.map((row) => <tr key={row.year} className="border-b border-[#edf0ec]"><td className="px-3 py-4 font-semibold text-[#173e39]">{row.year}</td><td className="px-3 py-4 text-right">{row.contractCount}</td><td className="px-3 py-4"><CurrencyAmounts values={row.expectedVatByCurrency} /></td><td className="px-3 py-4"><CurrencyAmounts values={row.netServiceIncomeByCurrency} /></td><td className="px-3 py-4"><CurrencyAmounts values={row.absorbedVatLossByCurrency} emphasis /></td></tr>)}</tbody></table></div>{!yearlyRows.length && <p className="py-10 text-center text-sm text-[#718079]">Yıllık mali özet için sözleşme kaydı bekleniyor.</p>}</CardContent></Card>
  </div>;
}
