import { useEffect, useMemo, useState } from "react";
import { AlertCircle, BarChart3, ReceiptText, RefreshCw, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { buildAuthorityPerformance, buildYearlyVatCollectionSummary, sumAuthorityPerformance, type ConsultantAuthorityPerformance } from "@/lib/authorityPerformance";
import { formatAuthorityCurrency } from "@/lib/authorityContract";
import { listOfflineRecords, type OfflineRecord } from "@/lib/offlineStore";

function CurrencyAmounts({ values, emphasis = false }: { values: Record<string, number>; emphasis?: boolean }) {
  const entries = Object.entries(values).filter(([, amount]) => amount > 0);
  return entries.length ? <div className="space-y-1">{entries.map(([currency, amount]) => <p key={currency} className={`whitespace-nowrap ${emphasis ? "font-semibold text-[#a85745]" : ""}`}>{formatAuthorityCurrency(amount, currency as "TRY" | "USD" | "EUR")}</p>)}</div> : <span className="text-muted-foreground">—</span>;
}

export default function OfflineConsultantPerformance() {
  const [records, setRecords] = useState<OfflineRecord[]>([]);
  const [updatedAt, setUpdatedAt] = useState("");
  const refresh = async () => { setRecords(await listOfflineRecords()); setUpdatedAt(new Date().toLocaleString("tr-TR")); };
  useEffect(() => { void refresh(); }, []);
  const rows = useMemo(() => buildAuthorityPerformance(records), [records]);
  const totals = useMemo(() => sumAuthorityPerformance(rows), [rows]);
  const yearlyRows = useMemo(() => buildYearlyVatCollectionSummary(records), [records]);

  return <div className="min-h-screen bg-[#f7f7f4] px-5 py-7 md:px-10 md:py-9"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.22em] text-[#a17b43]"><BarChart3 className="h-3.5 w-3.5" /> Offline performans görünümü</p><h1 className="font-serif text-4xl tracking-[-0.04em] text-[#223230]">Danışman Performansı ve KDV Takibi</h1><p className="mt-2 max-w-3xl text-sm text-[#70807c]">Yerel cihazdaki ve manager tarafından birleştirilmiş satış/kira sözleşmelerinden hesaplanır. KDV ayrıca tahsil edilmediyse tahsil edilen tutarın içindeki KDV ayrıştırılır ve net hizmet geliri kaybı gösterilir.</p></div><Button variant="outline" onClick={() => void refresh()} className="rounded-xl bg-white"><RefreshCw className="mr-2 h-4 w-4" /> Yenile</Button></header>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Toplam sözleşme</p><p className="mt-2 font-serif text-3xl text-[#173e39]">{totals.contractCount}</p><p className="mt-1 text-xs text-[#718079]">{totals.saleContractCount} satış · {totals.rentalContractCount} kira</p></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Hizmet bedeli (KDV hariç)</p><div className="mt-2 font-serif text-xl text-[#173e39]"><CurrencyAmounts values={totals.serviceFeeByCurrency} /></div></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Faturalı KDV toplamı (%20)</p><div className="mt-2 font-serif text-xl text-[#173e39]"><CurrencyAmounts values={totals.expectedVatByCurrency} /></div></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs text-muted-foreground">Net hizmet geliri</p><div className="mt-2 font-serif text-xl text-[#173e39]"><CurrencyAmounts values={totals.netServiceIncomeByCurrency} /></div></CardContent></Card><Card className="rounded-2xl border-[#ecd9d4] bg-[#fff9f7]"><CardContent className="p-5"><p className="text-xs text-[#a85745]">KDV içeride kaldığı için tahmini kayıp</p><div className="mt-2 font-serif text-xl"><CurrencyAmounts values={totals.absorbedVatLossByCurrency} emphasis /></div></CardContent></Card></div>
    <Card className="mb-6 rounded-2xl border-[#eadfca] bg-[#fffaf0]"><CardContent className="flex gap-3 p-4 text-xs text-[#7d6439]"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0" /><p><strong>Yönetim göstergesi:</strong> Satışta hizmet bedeli, sözleşmedeki tutar veya girilen oranla; kiralamada ise bir aylık kira ile hesaplanır. KDV ayrıca tahsil edildiyse net hizmet geliri değişmez. Tahsil edilen tutar KDV dâhil faturaya çevrildiyse, bu tutarın içindeki KDV ayrıştırılır ve <strong>tahmini kayıp</strong> olarak gösterilir. Bu rapor fatura/beyanname yerine geçmez; mali müşavirinizle teyit edin.</p></CardContent></Card>
    <Card className="rounded-2xl border-[#e5e8e3] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-xl"><UsersRound className="h-5 w-5 text-[#a17b43]" /> Danışman bazında hizmet bedeli ve KDV özeti</CardTitle><p className="text-xs text-[#87938f]">Son yenileme: {updatedAt || "yükleniyor"}. Para birimleri birbirine çevrilmez; her sütunda ayrı gösterilir.</p></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1160px] text-sm"><thead className="border-b text-left text-xs uppercase tracking-wide text-[#718079]"><tr><th className="px-3 py-3">Danışman</th><th className="px-3 py-3">Kod</th><th className="px-3 py-3 text-right">Satış / Kira</th><th className="px-3 py-3">Hizmet bedeli</th><th className="px-3 py-3">Faturalı KDV</th><th className="px-3 py-3">Net hizmet geliri</th><th className="px-3 py-3 text-[#a85745]">KDV içeride kayıp</th><th className="px-3 py-3">Son kayıt</th></tr></thead><tbody>{rows.map((row: ConsultantAuthorityPerformance) => <tr key={`${row.consultantCode}-${row.consultantName}`} className="border-b border-[#edf0ec] text-[#34433f]"><td className="px-3 py-4 font-medium"><span className="mr-2 inline-flex h-7 w-7 items-center justify-center rounded-full bg-[#e7efe9] text-xs font-bold text-[#173e39]">{row.initials}</span>{row.consultantName}</td><td className="px-3 py-4">{row.consultantCode || "—"}</td><td className="px-3 py-4 text-right font-semibold">{row.saleContractCount} / {row.rentalContractCount}</td><td className="px-3 py-4"><CurrencyAmounts values={row.serviceFeeByCurrency} /></td><td className="px-3 py-4"><CurrencyAmounts values={row.expectedVatByCurrency} /></td><td className="px-3 py-4"><CurrencyAmounts values={row.netServiceIncomeByCurrency} /></td><td className="px-3 py-4"><CurrencyAmounts values={row.absorbedVatLossByCurrency} emphasis /></td><td className="px-3 py-4">{row.latestContractDate || "—"}</td></tr>)}</tbody></table></div>{!rows.length && <div className="rounded-xl border border-dashed border-[#d7ded7] py-14 text-center text-sm text-[#718079]">Henüz performans tablosuna girecek bir offline satış veya kira sözleşmesi kaydı bulunmuyor.</div>}</CardContent></Card>
    <Card className="mt-6 rounded-2xl border-[#e5e8e3] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-xl"><ReceiptText className="h-5 w-5 text-[#a17b43]" /> Yıllık KDV tahsilat ve kayıp görünümü</CardTitle><p className="text-xs text-[#87938f]">Yıl bazında KDV’nin hizmet bedeli içinde kaldığı sözleşmelerin tahmini net gelir etkisini takip edin.</p></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="border-b text-left text-xs uppercase tracking-wide text-[#718079]"><tr><th className="px-3 py-3">Yıl</th><th className="px-3 py-3 text-right">Sözleşme</th><th className="px-3 py-3">Faturalı KDV</th><th className="px-3 py-3">Net hizmet geliri</th><th className="px-3 py-3 text-[#a85745]">Tahmini yıllık kayıp</th></tr></thead><tbody>{yearlyRows.map((row) => <tr key={row.year} className="border-b border-[#edf0ec]"><td className="px-3 py-4 font-semibold text-[#173e39]">{row.year}</td><td className="px-3 py-4 text-right">{row.contractCount}</td><td className="px-3 py-4"><CurrencyAmounts values={row.expectedVatByCurrency} /></td><td className="px-3 py-4"><CurrencyAmounts values={row.netServiceIncomeByCurrency} /></td><td className="px-3 py-4"><CurrencyAmounts values={row.absorbedVatLossByCurrency} emphasis /></td></tr>)}</tbody></table></div>{!yearlyRows.length && <p className="py-8 text-center text-sm text-[#718079]">Yıllık özet için sözleşme kaydı bekleniyor.</p>}</CardContent></Card>
  </div>;
}
