import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ShieldCheck, Users } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

export default function Team() {
  const { user } = useAuth();
  const members = trpc.team.list.useQuery(undefined, { enabled: user?.role === "admin", retry: false });
  if (user?.role !== "admin") return <div className="min-h-screen bg-[#f7f7f4] px-5 py-12 md:px-10"><Card className="mx-auto max-w-xl rounded-2xl border-[#ead6d0] bg-[#fff8f6]"><CardContent className="p-8 text-center"><ShieldCheck className="mx-auto mb-3 h-7 w-7 text-[#a85745]" /><h1 className="font-serif text-2xl text-[#34433f]">Manager yetkisi gerekli</h1><p className="mt-2 text-sm text-[#87938f]">Ekip ve hiyerarşi yönetimi yalnızca broker manager hesaplarına görünür.</p></CardContent></Card></div>;
  return <div className="min-h-screen bg-[#f7f7f4] px-5 py-7 md:px-10 md:py-9"><header className="mb-7"><p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.22em] text-[#a17b43]">Organizasyon</p><h1 className="font-serif text-4xl tracking-[-0.04em] text-[#223230]">Ekip yönetimi</h1><p className="mt-2 text-sm text-[#70807c]">Danışman kodu, ekip ve broker manager ilişkilerini yönetin.</p></header><Card className="rounded-2xl border-[#e5e8e3] bg-white/80"><CardHeader><CardTitle className="font-serif text-xl">Danışmanlar</CardTitle></CardHeader><CardContent>{members.isLoading ? <p role="status" className="py-10 text-center text-sm text-[#87938f]">Ekip yükleniyor…</p> : members.isError ? <p role="alert" className="py-10 text-center text-sm text-[#a85745]">Ekip verisi alınamadı.</p> : !members.data?.length ? <p className="py-10 text-center text-sm text-[#87938f]">Henüz ekip profili atanmadı.</p> : <div className="space-y-2">{members.data.map((member) => <div key={member.userId} className="flex flex-wrap items-center gap-4 rounded-xl border border-[#edf0ec] p-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#dce8e4] text-[#1c675c]"><Users className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-[#34433f]">{member.name || `Kullanıcı #${member.userId}`}</p><p className="mt-1 text-xs text-[#87938f]">{member.email || "E-posta belirtilmedi"} · {member.teamName || "Ekip atanmamış"}</p></div><span className="rounded-full bg-[#eef1ed] px-3 py-1 text-[10px] font-semibold text-[#60706b]">{member.officeRole === "broker_manager" ? "Broker Manager" : "Consultant"}</span></div>)}</div>}</CardContent></Card></div>;
}
