/* Generated from the user-provided, notere verilecek Teknik Şartname metninden (v9.1) — sabit ve tam metin. */
export const TECHNICAL_SPECIFICATION_FIXED_CLAUSES = [
  { partyScope: "shared" as const, title: `1. Genel Hükümler:`, bodyTemplate: `Proje kapsamındaki 4 villa ve 24 daireyi yürürlükteki deprem yönetmeliğine ve standartlara göre hazırlanmış olan mimari projesine, statik projesine, elektrik ve sıhhi tesisat, ısı yalıtım projesine uygun olarak yapılacak, Yapı Denetim firması tarafından denetlenecektir. Kullanılacak tüm ürünler TSE veya CE belgeli olacaktır. Kazı ve çevre emniyeti açısından her türlü güvenlik önlemleri alınacak ve gerekli iksa ve desteklemeler yapılacaktır. İSG önlemlerinin alınması ve çevreye gelebilecek her türlü zarar ve ziyanın tek sorumlusu ve tazmin edicisi Yüklenicidir. Konusunda uzman olan Yüklenici tüm riskleri öngörerek işbu sözleşmedeki paylaşım esaslarını kabul etmiştir; öngörülen ve/veya öngörülemeyen tüm riskler Yükleniciye aittir.
- Bu şartnamede yazan detaylar Mimar tarafından hazırlanan proje ve detayları ile farklı olması durumunda Mimari proje baz alınarak yapılacaktır. Şu kadar ki; mimari proje, işbu şartnamede belirtilen marka, model ve kalite standartlarının altına inemez.`, sortOrder: 5001, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `2. Zemin Etüdü ve Zemin İyileştirme:`, bodyTemplate: `Projenin tasarımı ve statik hesaplarında Türk Standartları ve 18 Mart 2018 tarihli 30364 sayılı "Türkiye Bina Deprem Yönetmeliği" (1 Ocak 2019 tarihinde yürürlüğe giren) şartlarına uygunluğu yanı sıra, zeminin ve temel sistemin jeoteknik değerlendirmeler ışığında jeolojik ve jeofizik araştırmalar yapılarak daire ve villalar için deprem açısından uygun zemin temel sistemini oluşturacak şekilde seçilecektir. Zemin etütleri doğrultusunda hazırlanan statik projeye göre zemin iyileştirmesi gerekli görülür ise iyileştirme yapılacaktır. Arsanın Zemin etüdü yapılarak bir geoteknik rapor düzenlenecek, burada zemin karakteristik periyotları, yerel zemin sınıfı, zemin grubu, zemin yatak katsayısı, zemin emniyet gerilmesi, yeraltı su durumu ve zemin kayma açısı belirlenecektir. Statik proje bu doğrultuda yapılacaktır.
Bina Temeli:
Bina temellerinde kullanılacak demir B420C (S420) nervürlü demir kullanılarak yapılan statik projesine uygun olarak hazırlanacaktır.
Temel altı uygulaması (Aşağıdan yukarıya doğru):
- 10 cm C30 Grobeton
- HYPERFLEX PROOF Membran 3,5 mm
- Yalıtıma uygun 5 cm pas payı`, sortOrder: 5002, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `3. Perde Beton ve Dolgu:`, bodyTemplate: `Zemin izolasyonu açısından temelden, zemin betonuna kadar Membran uygulaması ve XPS ile kaplanarak ısı ve su yalıtımı yapılacaktır. (Bohçalama)
Perde beton su yalıtım detayları (Bina içinden dışına doğru):
- HYPERFLEX PROOF Membran 3,5 mm uygulaması zemin betonuna kadar kaplanacaktır.
- Mekanik projesine göre belirlenen XPS kalınlığı 4 cm olacak şekilde XPS blokları zemin betonuna kadar kaplanacaktır.
- XPS üzerine 13,5 tuğla ile koruma duvarı yapılacaktır.
- Perde içi dolgu olarak nitelikli baypass veya 2 numara mıcır kullanılarak dolgu yapılacaktır.`, sortOrder: 5003, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `4. Zemin Blokaj Betonu:`, bodyTemplate: `- 4 cm XPS ile ısı yalıtım koruması yapılacaktır.
- 15 cm C30 ile blokaj betonu dökülecektir.`, sortOrder: 5004, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `5. Bina Dış Duvarları:`, bodyTemplate: `- Bina dış duvarlarında 19 cm kalınlığında dikey delikli tuğla, iç duvarlarda 19 cm kalınlığında yatay delikli tuğla kullanılacaktır.
- Bina dış duvarlarında yapılacak Granit kaplama sisteminde mekanik kaplama yöntemi kullanılacak olup granit duvar arasında Taş Yünü ve Buhar Kesici kullanılacaktır.
- Bina dış duvarlarında uygulanacak taş duvar mimari projesine uygun olarak hazırlanacaktır.`, sortOrder: 5005, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `6. Isı – Su Yalıtım Sistemleri:`, bodyTemplate: `- Bina kolon ve kiriş bölümleri 150 yoğunluk 5 cm Taş Yünü Isı Yalıtım Levhaları ile kaplanacaktır.
- Su yalıtımı olarak Weber – BASF – Sika markalı ürünler kullanılacaktır.`, sortOrder: 5006, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `7. Sıvalar:`, bodyTemplate: `- Alçı sıvalar düzgünlüğü sağlamak amacıyla gönyeli olarak uygulanacak olup, tüm köşelerde köşe profili, duvar elemanı ile betonarme elemanların birleşim yerlerinde sıva filesi uygulaması yapılacaktır.
- Sıva uygulamalarından önce betonarme yüzeylerde aderans arttırıcı kullanılacaktır.
- 4 villa ve 24 daireden oluşan bağımsız bölümlerin iç cephesindeki tüm iç duvar ve tavan (banyolar hariç) sıvaları kaba alçı sıva ile sıvanacak, kullanılacak olan alçı sıva Lafarge veya Knauf marka olacaktır. Sonra üzerine el ile saten alçısı çekilecektir.`, sortOrder: 5007, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `8. Duvar Boyaları:`, bodyTemplate: `- Tüm duvarlarda ve tavanda kullanılacak boya markası JOTUN olacaktır.
- İç duvarlarda su bazlı saten boya kullanılacaktır.`, sortOrder: 5008, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `9. Doğramalar:`, bodyTemplate: `- Bina dış cephe doğramaları Linea Rossa marka LR3200 model ısı yalıtımlı alüminyum doğrama ve sineklikli olacaktır. Bina dışına yapılan doğramalar hiçbir koşulda PVC olmayacaktır. Doğrama ölçülerine uygun 4+16+4 konfor ısıcam kullanılacaktır.
- Doğrama kaplamaları Ekosal olarak imal edilecektir.
- Kullanılacak doğramalarda PVC yalıtım köprüsü yapılarak ısı yalıtımlı olarak imal edilecektir.`, sortOrder: 5009, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `10. Panjurlar:`, bodyTemplate: `- Yapılacak olan otomasyon sistemine bağlı olarak çalışacaktır.
- Her panjurun yanında manuel olarak kapatma ve açma anahtarları bulunacaktır.
- Somfy veya Mosel motorlu, alüminyum poliüretan panelli, kör kasa ve gizli olacaktır.`, sortOrder: 5010, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `11. Kapı ve Pervaz:`, bodyTemplate: `- İç oda kapıları Yıldız Entegre'nin Soho serisi olacaktır. Kasa ve pervazları MDF üzeri İpek Mat Lake su bazlı akrilik boya veya doğal ahşap kaplama, oda kapısı kanatları MDF üzeri Lake boya ile ipek mat vernik veya doğal ahşap kaplama yapılacaktır. Bina giriş kapısı kasa ve kanadı MDF üzeri lake veya doğal ahşap kaplama olacaktır.
- Kullanılan tüm kapılarda kapı kolları HAFELE-SAMET marka olacaktır.
- Villa ve Daire girişlerinde Sur marka çelik kapı, Train modeli, MUL-T-LOCK Merkezi 315G İntegratör Barel kilit sistemi takılacaktır.`, sortOrder: 5011, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `12. Dolaplar:`, bodyTemplate: `Mutfak Dolapları:
Gövdeler 1. Sınıf Çamsan veya Agt marka MDF lam, kapaklar akrilik veya MDF üzeri lake boya olacaktır. Tüm çekmeceler HAFELE–SAMET tandem box'lı, tüm menteşeler HAFELE-SAMET olacaktır. Tezgâh yüzeyi ve tezgâh arası (sıçrama payı) duvar kaplaması, en az 2 cm kalınlığında kuvars kompozit (mühendislik taşı) veya muadili doğal taş olacaktır. Mutfağa bulaşık makinası tesisatı, sıcak – soğuk su tesisatı çekilecektir. Banko üzeri ve altına topraklı priz, anahtar konulacaktır. Mutfak dolap içi aydınlatmalı yapılacaktır.
Banyo Dolapları:
Duvara uygun MDF üzeri ipek mat lake, su bazlı akrilik boya veya doğal ahşap gövdeli, aynalı, etejerli, lavabolu altı kapaklı Hilton dolaplar yapılacaktır. Tüm menteşeler ve kulplar HAFELE-SAMET olacaktır.
Çamaşır odasında sıcak-soğuk su tesisatı çekilecektir. Çamaşır odası dolapları HAFELE–SAMET marka menteşeler ve kulplar kullanılacaktır.
Gömme Dolaplar:
Odalarda projesine uygun olarak MDF üzeri mat lake su bazlı akrilik boya veya doğal ahşap kaplama gömme dolap yapılacaktır. Menteşe ve kulpları HAFELE–SAMET marka olacaktır. Dolap kapaklarından birine 1 boy ayna takılacaktır. Vestiyer bölümü için de aynı özelliklerde gömme dolap yapılacaktır.
Dairelerde her iki yatak odası için, villalarda ise her üç yatak odası için ayrı ayrı gömme dolap (gardrop) yapılacaktır. Gardrobun oda içindeki konumu, iç mekân dolaşımını ve mobilya yerleşimini engellemeyecek şekilde, mimari projede odanın uygun bir cephesine planlanır.
Bina Giriş Dolapları:
Bina girişlerinde ve/veya vestiyer bölümünde yapılacak dolaplarda menteşeler HAFELE-SAMET markası olacaktır. MDF üzeri mat lake su bazlı akrilik boya veya doğal ahşap kaplama yapılacaktır.`, sortOrder: 5012, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `13. Taban Döşeme Kaplamaları:`, bodyTemplate: `- Banyo tabanları seçilen duvar kaplamasına uygun birinci sınıf Kütahya Seramik (kaydırmaz) kaplama ile yapılacak olup 60x120 ebatlarında olacaktır.
- Salon, yatak odası, mutfak, antre ve koridor taban döşemeleri birinci sınıf Kütahya Seramik marka seramik kaplama ile yapılacaktır.`, sortOrder: 5013, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `14. Ana Merdivenler:`, bodyTemplate: `- Betonarme merdiven olacaktır.
- Merdiven üzeri 1. Sınıf mermer kaplama olacaktır.
- Bina içi merdiven aydınlatmaları LED ampul olacaktır.
- B ve C Blok ikiz villaların iç merdivenleri betonarme olacak; basamaklar 1. Sınıf mermer kaplanacak, korkulukları projesine uygun olarak imal edilecektir.
- A Blok 1 ve 5 numaralı bağımsız bölümlerin ofis kullanımına yönelik iç merdiveni, bu amaçla hazırlanacak proje ve madde 29 kapsamındaki arsa sahipleri onayı çerçevesinde kesinleştirilir.`, sortOrder: 5014, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `15. Mutfak:`, bodyTemplate: `- Mutfak eviyesi Franke Basis BFG 651-97 Bianco Granit Evye veya Teka Stone 60 B-TG beyaz granit eviye olacaktır.
- Mutfaktaki eviye bataryası Franke Active Plus Doccia 2.0 Spiralli Bianco veya Teka Oval 914 Beyaz Eviye Bataryası olacaktır.
- Mutfağa Franke marka 4'lü ankastre set konulacaktır: Bulaşık Makinesi (FDWS 614 D8P DOS E), Ocak (FHNS 604 4G BK C, Siyah Cam), Davlumbaz (FPJ 615 V BK A/600, Siyah Cam), Fırın (Smart Linear Digital FSL 86 H BK).
- Tüm bağımsız bölümlerde mutfak açık mutfak olacaktır. Mimari projede salona ada mutfak yapılmasının uygun görülmesi hâlinde; ada gövdesi, tezgâh yüzeyi ve tezgâh arası (sıçrama payı) duvar kaplaması, en az 2 cm kalınlığında kuvars kompozit (mühendislik taşı) veya muadili doğal taş ile bütünlük içinde kaplanır. Mimari yerleşimin ada mutfağa elvermemesi hâlinde, tezgâh düzeni madde 12'deki esaslara göre uygulanır.
- Çekmeceler teleskopik raylı ve stoperli, dolaplar stoperli olacaktır.`, sortOrder: 5015, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `16. Banyo:`, bodyTemplate: `- Yapılacak olan lavabolarda VitrA Outline Çanak Lavabo kullanılacaktır. Lavabo tezgâhı, en az 2 cm kalınlığında kuvars kompozit (mühendislik taşı) veya muadili doğal taş olacaktır.
- Banyoda kullanılacak lavabo bataryası VitrA Minimax Round A43532 model olacaktır.
- Tüm rezervuarlar VitrA QuantumFlush Asma Klozet ile uyumlu gömme rezervuarlı olacaktır.
- Duş mahali walk-in sistemli olacak şekilde Özel İmalat olarak uygulanacak; duş bataryası VitrA Origin Krom Ankastre Tepe Duş Seti (Model: 7910B403-0090) olacaktır. Walk-in duş bölmesi, en az 8 mm kalınlığında temperli (kırılmaya dayanıklı) cam ile kapatılacaktır.
- Nişli duş mahali ve tuvalet üstü niş uygulaması olacaktır.
- Tüm banyo ve WC havalandırmalarında Bosch 1700 serisi fan kullanılacaktır.`, sortOrder: 5016, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `17. Duvar Kaplamaları ve Yer Kaplamaları:`, bodyTemplate: `Pencere denizlikleri, balkon kenarları, sürme kapıların altı, çelik kapıların ve banyo kapılarının eşikleri 3 cm kalınlığında 1. Sınıf mermerden olacaktır.`, sortOrder: 5017, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `18. Sıhhi Tesisat:`, bodyTemplate: `Her bağımsız bölüm için, ilgili bağımsız bölümün ısıtma ve yerden ısıtma ihtiyacına yeterli kapasitede olmak üzere, dairelerde en az 24 kW (20.000 kcal/h), villalarda en az 28 kW (24.000 kcal/h) kapasiteli Demirdöküm tam yoğuşmalı doğalgaz kombi ve kablolu dijital duvar termostatı yapılacaktır. Kesin kapasite, mekanik projede ısı kaybı hesabına göre belirlenir ve bu maddedeki değerlerin altında olamaz.
Temiz su tesisatı boruları Wavin veya Fırat – Cam Elyaf takviyeli PPRC beyaz boru olacaktır.
Pis su tesisatı Wavin veya Fırat Sessiz siyah PVC boru kullanılacaktır.
Tüm banyo ve mutfak bölümüne sıcak su temini sağlanacaktır.
Binadaki teras, balkon vb. alanlara musluk yapılacaktır.`, sortOrder: 5018, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `19. Elektrik Tesisatı:`, bodyTemplate: `Elektrik Mühendisleri Odasının ve ilgili belediyenin tasdik ettiği proje esaslarına aynen uyulacak ve bütün montaj malzemeleri TSE ve ISO belgeli olacaktır.
Tüm Villalar ve Daireler için topraklama tesisatı yapılacaktır. 1. kalite kablolar ÖZNUR, HES veya ALTIN marka ve 1. kalite montaj malzemeleri kullanılacaktır.
Her bir Villa/Dairede aşağıdaki lokasyonlara, belirtilen asgari sayıda TSE belgeli VİKO marka topraklı priz tesis edilecektir:
- Salon: 10 adet
- Ebeveyn yatak odası: 6 adet
- Diğer yatak odaları (villalarda 2 adet): 5'er adet
- Mutfak: 8 adet (ada mutfak yapılması hâlinde ada üzerinde ayrıca en az 2 adet dâhil)
- Banyo (her biri için): 3 adet
- Çamaşır makinesi ve kurutma makinesi bağlantı noktaları: 2 adet, ilgili mevzuat gereği müstakil hat ile beslenecek şekilde
- Antre: 1 adet
- Koridor: 1 adet
- Balkon (her biri için): 1 adet
- Villalarda zemin kat bahçe terası: 2 adet
Çamaşır makinesi ve kurutma makinesi bağlantı noktaları; mimari projede ayrı bir çamaşır odası öngörülmesi hâlinde o mahalde, öngörülmemesi hâlinde (villalarda olduğu gibi) banyoda tesis edilir; bu durumda banyodaki toplam priz sayısı, yukarıdaki iki kalemin toplamı (5 adet) olur.
Banyo, balkon ve bahçe terasındaki prizler, ilgili elektrik iç tesisat yönetmeliği ve TSE standartlarına uygun mesafede konumlandırılacak ve en az IP44 koruma sınıfına sahip, kapaklı modellerden seçilecektir. Villaların iki katlı olması nedeniyle, yukarıdaki sayılar her bir kat için ayrı ayrı uygulanır; villaların çatı yapısı (madde 27) nedeniyle çatı terası bulunmaz.
Aydınlatma anahtarları ve prizleri mimarların planladığı şekilde tefrişata uygun olarak projelendirilecek ve uygulanacaktır.
Villaların ve Dairelerin tablolarında, LEGRAND marka otomatik sigorta kullanılacaktır. Her Villa/Daire için kaçak akım rölesi kullanılacaktır.
Elektrik priz ve lamba anahtarları VİKO marka olacaktır. Tüm priz tesisatı topraklı olarak, sigorta panoları otomatik sigortalarla teçhiz edilecektir. Ana sayaç panolarında yangın koruma şalteri bulunacaktır. Her Villa/Dairenin tesisatı 9 kW talep gücüne göre trifaze sözleşmeye uygun olarak çekilecek, kuvvet tesisatı bağımsız hat olacaktır.
Villa/Daire topraklama hatları ana topraklamaya bağımsız hatla elektrik projesinde hesap edilen kablo ile bağlanacaktır.
Sitenin ortak otopark alanlarında, ileride elektrikli araç AC şarj üniteleri kurulabilmesi amacıyla, park yerlerinin bir kısmına önceden altyapı hazırlanacaktır. Bu kapsamda; ilgili park yerlerinden ana elektrik panosuna kadar boş kablo kanalı çekilecek, panoda bu amaçla ayrılmış sigorta yeri bırakılacak ve altyapı en az 22 kW'a kadar AC şarj ünitesi kurulumuna uygun kapasitede projelendirilecektir. İşbu madde yalnızca altyapı hazırlığını kapsar; şarj ünitelerinin bizzat temini ve montajı bu madde kapsamı dışındadır.
A Blok 1 ve 5 numaralı bağımsız bölümlere (ofis) tahsis edilen park yerlerinde de aynı altyapı standardı uygulanır.
Arsa Sahiplerine isabet eden Villa/Dairelerin elektrik, su ve doğalgaz abonelikleri ile bu aboneliklere ait güvence bedelleri, bedeli ilgili Arsa Sahibi tarafından karşılanmak üzere, Yüklenici tarafından tesis ettirilecektir.
Her Villa/Daireye merkezi olacak şekilde Digiturk, D-Smart ve merkezi uydu altyapısı kurulacaktır.
Salonda, her odada ve Mutfakta TV bağlantısı olacaktır.
Her Villa/Daireye fiber optik internet hatları çekilecektir. Tüm Villa/Daireye İnternet dağıtımı ile ilgili altyapı hazırlanacaktır. Villa/Dairelerde projesine uygun olarak telefon tesisatı yapılacaktır; bu tesisat Villa/Daire içinde salon ve ebeveyn odası arasında dağıtılacaktır. Telefon kabloları TSE ve CE belgeli, Cat6 kablo olacaktır.`, sortOrder: 5019, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `20. Bina Otomasyon Sistemleri:`, bodyTemplate: `Sitenin caddeye açılan her iki ana giriş noktası da, görüntülü diafon (interkom) sistemine bağlı olacak şekilde projelendirilecektir. Her bağımsız bölüme bu sisteme bağlı bir iç ünite tesis edilecek ve santral montajı yapılacaktır.
Mutfaktaki ocak üzerine ısı artış dedektörü kullanılacaktır.
Bahçe sulama sisteminin (madde 24 kapsamında tesis edilen fiziksel tesisatın) otomatik ve programlanabilir kontrolü sağlanacaktır.
Panjurların kontrolü, madde 10'daki otomasyon sistemi üzerinden sağlanacaktır.`, sortOrder: 5020, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `21. Tesisat İklimlendirme – Isıtma ve Soğutma Sistemi:`, bodyTemplate: `Villa ve daire salonlarına SAMSUNG marka 24.000 Btu'luk kaset tipi klima takılacaktır. Dairelerde, salon dışındaki iki yatak odasına, oda büyüklüğüne yeterli kapasitede (yaklaşık 9.000–12.000 Btu aralığında) SAMSUNG marka duvar tipi inverter klima takılacaktır.
Multi klima sisteminin dış üniteleri; A, D ve E Blok dairelerde çatı terasında, villalarda (B ve C Blok) ise mimari projede belirlenecek uygun bir noktada yerleştirilecek; görüntü kirliliği oluşturmayacak, yeterli havalandırmayı sağlayacak ve kıyı bölgesinin tuzlu-nemli iklim koşullarından etkilenmeyecek şekilde muhafaza edilecektir.
Fraenkische marka yerden ısıtma sistemi kurulacak olup yerden ısıtma için kullanılan boru çapları 16 mm PX-A tipi olacaktır.`, sortOrder: 5021, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `22. TV Anteni:`, bodyTemplate: `Vaziyet planında uydu yönleri ve mimarın belirleyeceği bir noktaya TURKSAT, HOTBİRD ve DİGİTURK yayınlarını alabilen gerekli çaplarda uydu antenler konulacaktır. Yapılacak olan tesisatta RG6 U4 tipi anten kablosu kullanılacaktır. Anten sortileri yatak odaları, tüm odalar, mutfak, salon, villalarda bahçe terası ve dairelerde çatı teras katına ise madde 26 kapsamında erişimi olan bağımsız bölümlerde yapılacaktır. Ayrıca evin tamamına DİGİTÜRK kablo hazırlığı yapılacaktır.`, sortOrder: 5022, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `23. Su Temini:`, bodyTemplate: `Tüm villa ve dairelere şehir suyu bağlantısı yapılacaktır. Bahçe sulaması ve havuzun su ihtiyacının karşılanması amacıyla artezyen kuyusu açılacaktır. Havuzun makine dairesi yanına, artezyen kaynağından beslenen bir su deposu yapılacak ve hidrofor tesis edilecektir. Artezyen suyu yalnızca bahçe sulaması ve havuz amaçlı kullanılacaktır.`, sortOrder: 5023, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `24. Peyzaj – Bahçe:`, bodyTemplate: `Bu madde kapsamındaki peyzaj uygulamaları, 4 villa ve 24 daireden oluşan projedeki tüm bağımsız bölümler için geçerlidir.
- Bahçe giriş kapıları, kolay deforme olmayacak malzeme kalınlığına sahip demir/alüminyum doğrama ile yapılacaktır.
- Bahçe aydınlatmaları top globlardan oluşacaktır. Otomatik bahçe sulaması ve peyzaj çalışmaları yapılacaktır.
- Bahçeye 25 cm bahçe toprağı atılıp hazır rulo çim uygulaması yapılacaktır.
- Her bağımsız bölümün mimari projede belirtilen sınırlarına 50 cm ara ile en az 150 cm yüksekliğinde taflan (Prunus laurocerasus) veya kartopu (Viburnum opulus) çit bitkisi dikilecektir.
- Bahçe ve bina dış aydınlatmaları LED ampul olacaktır.`, sortOrder: 5024, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `25. Havuz:`, bodyTemplate: `Bu madde kapsamındaki havuz, projenin ortak kullanım alanı olup 4 villa ve 24 daireden oluşan sitenin tamamı için ortak bir havuz olarak inşa edilecektir.
- C35 beton kullanılacaktır.
- Perde betonlarında su yalıtımı olarak TEKNOMER bant uygulanacaktır.
- Perde iç yüzeylerinde ve savaklarda WEBER marka reçineli pah bandı ve SS10 sürme esaslı yalıtım uygulanacaktır.
- Havuz yapıştırıcılarında Weber marka Ultraflex beyaz yapıştırıcı kullanılacaktır.
- MOSSAİCA BTB seramik uygulaması yapılacaktır.
- GEMAŞ Filtrasyon sistemi, havuzun suyunu düzenli olarak temizleyip yenileyecek yeterli kapasitede kurulacaktır.
- Su dezenfeksiyonu otomatik bir klorlama sistemiyle sağlanacak, havuz suyu ısıtılmayacaktır.
- Havuzun makine dairesi ayrı bir bölüm olarak yapılacak ve pompa, filtre gibi ekipmanları içerecektir.
- Havuz çevresinde kaymaz zeminli bir güneşlenme terası yapılacaktır.`, sortOrder: 5025, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `26. Çatı Teras Katı:`, bodyTemplate: `A, D ve E Bloklarının çatı katlarına, birinci sınıf malzemeden camlı kışlık bahçe yapılacaktır. Kışlık bahçe kuzey ve güney olmak üzere iki bölüme ayrılır; bir bölümü ilgili blokta zemin (bahçe) katındaki bağımsız bölüm malikinin, diğer bölümü ise üst kattaki bağımsız bölüm malikinin münhasır (özel) kullanımına tahsis edilir. Hangi yönün hangi malike ait olduğu, her bir bölümün kullanım alanı (m²) ve kışlık bahçenin sabit kapalı mı yoksa üstü açılır sistemli mi (örn. bioclimatic pergola/retractable çatı) yapılacağı, mimari proje kesinleştiğinde belirlenir ve yönetim planında (EK-3) açıkça gösterilir.`, sortOrder: 5026, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `27. Çatı Sistemleri ve Site Çevre Düzeni:`, bodyTemplate: `- Villaların çatısı BRAAS sistemli kapalı çatı olacaktır.
- Site çevre duvarı; projesinde belirtildiği şekilde 50-100 cm yüksekliğinde bahçe duvarı ve duvarların üstü de lazer kesim metal olacaktır.
- Dairelere ait blokların çatı teraslarında ısı ve su geçirmezliğinin sağlanabilmesi için projesine uygun olarak gerekli yalıtım malzemeleri ve levhalarla mantolanacaktır.
- Site adı kesinleştikten sonra, sitenin caddeye açılan her iki yol cephesine de site adının yazılı olduğu ışıklı tabela yaptırılacaktır. Site ortak alan aydınlatmaları ve isim tabelası, site ortak elektrik sayacına bağlanacaktır.`, sortOrder: 5027, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `28. Garanti Süreleri:`, bodyTemplate: `- Daire ve villalarda kullanılan mekanik, elektrik tesisatı, beyaz eşya ve sıhhi tesisat ürünlerinde, bağımsız bölümün kullanıma başlangıç tarihinden itibaren 24 ay ürün garantisi uygulanacaktır.
- İnşaat işlerine ilişkin olarak, Türk Borçlar Kanunu'nun ilgili hükümleri uyarınca yüklenicinin yapıdaki ayıplardan sorumluluğu, eserin teslim tarihinden itibaren 5 yıldır.
İşbu maddedeki ürün garantileri üretici/ithalatçı garantisi olup, sözleşmenin 13. maddesinde düzenlenen yüklenicinin 5 (beş) yıllık giderim yükümlülüğünü sınırlamaz.`, sortOrder: 5028, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `29. Ofis Eklentisi (A Blok 1 ve 5):`, bodyTemplate: `A Blok 1 ve 5 numaralı bağımsız bölümlerin her ikisi de ofis (büro) kullanımına yönelik olarak projelendirilir. Bu kapsamda; yönetim odaları, müşterilerle görüşme bölümleri ile projenin renk ve güncel/modern konsepti belirlenir ve sözleşmenin 10. maddesindeki 90 günlük mimari proje takvimi kapsamında, daire ve villa çizimleriyle birlikte vekilin yazılı onayına sunulur.
Ofis kapalı odalarının iklimlendirmesi, mimari çizimlerle kesinleşecek oda bölünmesi ve alan büyüklükleri esas alınarak yapılacak ısıtma/soğutma yükü hesabı çerçevesinde planlanır ve gerekli klima adedi bu hesaba göre belirlenir. Açık çalışma alanı ile tavana kadar duvarla bölünmemiş alanlar için ayrı klima öngörülmez. Kesin klima adedi ve yerleşimi, ofis kullanım projesi kesinleştiğinde madde 29 kapsamındaki onay süreciyle birlikte netleştirilir.
A Blok 1 ve 5 numaralı bağımsız bölümlerin ofis olarak kullanılacak olması nedeniyle, zemin ve 1. kat cepheleri üç yönden doğramalı olarak projelendirilebilir. Bu şekilde oluşacak ilave doğrama alanı, madde 9'da belirtilen malzeme ve kalite standardına tabi olup yüklenicinin taahhüdü kapsamındadır; ayrıca bir bedel talep edilemez.`, sortOrder: 5029, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
  { partyScope: "shared" as const, title: `30. Dış Cephe Tasarımı ve Onaylanması:`, bodyTemplate: `Yüklenici; bina dış cephelerine ilişkin (cephe malzemesi, renk, doku, granit/taş kaplama deseni ve doğrama görünümü dahil) mimari cephe tasarımını, yapı ruhsatı başvurusundan önce görsel/teknik sunum (render, cephe kesiti ve malzeme numuneleri) halinde Arsa Sahiplerine sunmakla yükümlüdür. Arsa Sahipleri, sunulan tasarıma ilişkin görüş ve itirazlarını sunum tarihinden itibaren 15 gün içinde yazılı olarak bildirir; bu süre içinde itiraz bildirilmemesi hâlinde tasarım onaylanmış sayılır. Taraflar arasında cephe tasarımı konusunda mutabakat sağlanamaması hâlinde, işbu şartnamenin 5. ve 9. maddelerinde belirtilen asgari malzeme ve kalite standartları esas alınır.
Yukarıda belirtilen tüm Teknik Şartname ve tüm Masraflar yükleniciye aittir.`, sortOrder: 5030, status: "active" as const, sourceNote: "Kullanıcının sağladığı, notere verilecek Teknik Şartname (EK-1) metni" },
] as const;
