import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createRentalFixtureItem, fixtureItemsFromLegacy, fixtureItemsToLegacy, type OfflineRentalDetails, type RentalFixtureItem } from "@/lib/rentalContract";

type Props = { details: OfflineRentalDetails; onChange: (next: OfflineRentalDetails) => void };

/** Claude kira şablonunun satır ekleme/silme davranışını offline snapshot modeline taşır. */
export default function RentalFixturesEditor({ details, onChange }: Props) {
  const rows = details.fixtureItems?.length ? details.fixtureItems : fixtureItemsFromLegacy(details.fixtures);
  const setRows = (nextRows: RentalFixtureItem[]) => onChange({ ...details, fixtureItems: nextRows, fixtures: fixtureItemsToLegacy(nextRows) });
  const update = (id: string, key: keyof Omit<RentalFixtureItem, "id">, value: string) => setRows(rows.map((row) => row.id === id ? { ...row, [key]: value } : row));
  const remove = (id: string) => setRows(rows.filter((row) => row.id !== id));
  return <div className="sm:col-span-2"><div className="mb-1.5 flex flex-wrap items-center justify-between gap-2"><div><label className="block text-xs font-semibold text-[#56635f]">Demirbaş listesi</label><p className="mt-0.5 text-[11px] text-[#87938f]">Cinsi / markası, adet ve teslim durumunu satır bazında girin. İstediğiniz kadar satır ekleyebilirsiniz.</p></div><Button type="button" size="sm" variant="outline" onClick={() => setRows([...rows, createRentalFixtureItem()])} className="border-[#b8c9c3] bg-white text-[#173e39]"><Plus className="mr-1 h-3.5 w-3.5" /> Satır ekle</Button></div><div className="overflow-x-auto rounded-lg border border-[#dbe5dd] bg-white"><table className="min-w-[620px] w-full border-collapse text-sm"><thead className="bg-[#eff5f2] text-left text-xs font-semibold text-[#43534e]"><tr><th className="w-12 border-b border-[#dbe5dd] px-3 py-2 text-center">#</th><th className="border-b border-[#dbe5dd] px-3 py-2">Cinsi / Markası</th><th className="w-28 border-b border-[#dbe5dd] px-3 py-2">Adet</th><th className="border-b border-[#dbe5dd] px-3 py-2">Teslim Durumu</th><th className="w-12 border-b border-[#dbe5dd] px-2 py-2"><span className="sr-only">Satırı sil</span></th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id} className="border-b border-[#edf1ef] last:border-0"><td className="px-3 py-1 text-center text-xs text-[#71807b]">{index + 1}</td><td className="p-1"><Input value={row.item} onChange={(event) => update(row.id, "item", event.target.value)} placeholder="Örn. Vestel klima, ankastre set" className="h-9 border-transparent bg-transparent shadow-none focus-visible:border-[#1c554c] focus-visible:ring-1" /></td><td className="p-1"><Input inputMode="numeric" value={row.quantity} onChange={(event) => update(row.id, "quantity", event.target.value.replace(/[^0-9]/g, ""))} placeholder="1" className="h-9 border-transparent bg-transparent shadow-none focus-visible:border-[#1c554c] focus-visible:ring-1" /></td><td className="p-1"><Input value={row.condition} onChange={(event) => update(row.id, "condition", event.target.value)} placeholder="Çalışır, temiz, hasarsız" className="h-9 border-transparent bg-transparent shadow-none focus-visible:border-[#1c554c] focus-visible:ring-1" /></td><td className="p-1 text-center"><Button type="button" variant="ghost" size="icon" onClick={() => remove(row.id)} aria-label={`${index + 1}. demirbaş satırını sil`} className="h-8 w-8 text-[#a4594f] hover:bg-[#fdf2f0] hover:text-[#8b4038]"><Trash2 className="h-3.5 w-3.5" /></Button></td></tr>)}</tbody></table></div>{rows.length === 0 && <p className="mt-2 text-xs text-[#87938f]">Liste boş. Teslim edilen her demirbaş için “Satır ekle” düğmesini kullanın.</p>}</div>;
}
