import { calculateRentalSummary, rentalFixtureSummary, type OfflineRentalDetails } from "@/lib/rentalContract";
import { RENTAL_CONDITIONS_TEMPLATE_VERSION, rentalContractConditions } from "@/lib/rentalConditions";
import React from "react";

type RentalContractDocumentProps = { details: OfflineRentalDetails; contractNo: string; fontSize: string };
const value = (text: string) => text.trim() || "................................";
const money = (amount: number) => amount ? `${new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 0 }).format(amount)} ₺` : "................................";
const consultantInitials = (name: string) => name.trim().split(/\s+/).filter(Boolean).map((part) => part.slice(0, 1).toLocaleUpperCase("tr-TR")).join("") || "—";
const appendixLabel = { evacuation: "Tahliye Taahhütnamesi", handover: "Teslim Etme Formu", return: "Teslim Alma Formu", fixtures: "Demirbaş Listesi" } as const;

function Row({ firstLabel, firstValue, secondLabel, secondValue }: { firstLabel: string; firstValue: string; secondLabel?: string; secondValue?: string }) {
  return <tr><th scope="row">{firstLabel}</th><td>{value(firstValue)}</td>{secondLabel && <><th scope="row">{secondLabel}</th><td>{value(secondValue ?? "")}</td></>}</tr>;
}

export default function RentalContractDocument({ details, contractNo, fontSize }: RentalContractDocumentProps) {
  const summary = calculateRentalSummary(details);
  const kind = details.useType === "commercial" ? "İŞYERİ KİRA SÖZLEŞMESİ" : "KONUT KİRA SÖZLEŞMESİ";
  const conditions = rentalContractConditions(details, summary.endDate);
  const selectedAppendices = Object.entries(details.appendixSelection).filter(([, included]) => included).map(([kind]) => appendixLabel[kind as keyof typeof appendixLabel]).join(" · ");
  return <article className="authority-print-document authority-contract-document rental-contract-document bg-[#fff] text-[#1c2524]" style={{ "--authority-print-font-size": `${fontSize}pt` } as React.CSSProperties}>
    <header className="rental-document-header"><p className="rental-document-record">Kira sözleşmesi kaydı: {value(contractNo)}</p></header>
    <div className="authority-document-rule" /><h2 className="authority-document-title">{kind}</h2><p className="authority-document-meta">Düzenleme Tarihi: <strong>{value(details.startDate)}</strong> · Belge yeri: <strong>{value(details.documentPlace)}</strong></p>
    <section className="authority-document-section"><h3>KİRAYA VEREN VE KİRACI BİLGİLERİ</h3><table><tbody><Row firstLabel="Kiraya Veren" firstValue={details.ownerName} secondLabel="T.C. Kimlik No / VKN" secondValue={details.ownerIdentity} /><Row firstLabel="Kiraya Veren Adresi" firstValue={details.ownerAddress} secondLabel="Telefon" secondValue={details.ownerPhone} /><Row firstLabel="Kiracı" firstValue={details.tenantName} secondLabel="T.C. Kimlik No / VKN" secondValue={details.tenantIdentity} /><Row firstLabel="Kiracı Adresi" firstValue={details.tenantAddress} secondLabel="Telefon" secondValue={details.tenantPhone} /></tbody></table></section>
    <section className="authority-document-section"><h3>TAŞINMAZ, BEDEL VE SÜRE BİLGİLERİ</h3><table><tbody><Row firstLabel="Mahalle / Yerleşim" firstValue={details.propertyNeighborhood} secondLabel="Taşınmaz Açık Adresi" secondValue={details.propertyAddress} /><Row firstLabel="Niteliği / Cinsi" firstValue={details.propertyType} secondLabel="Ada / Parsel / B.B." secondValue={details.parcelInfo} /><Row firstLabel="Kullanım Amacı" firstValue={details.usagePurpose} secondLabel={details.useType === "commercial" ? "KDV Durumu" : "İkamet Edecek Kişi"} secondValue={details.useType === "commercial" ? (details.kdvIncluded ? "KDV dâhil" : "KDV hariç") : details.residentsCount} /><Row firstLabel="Aylık Kira Bedeli" firstValue={money(summary.monthlyRent)} secondLabel="Depozito" secondValue={money(Number(details.deposit.replace(/\./g, "").replace(",", ".")))} /><Row firstLabel="İlk Kira Son Ödeme Tarihi" firstValue={`${summary.firstDueDate} (en geç 5 gün)`} secondLabel="Sözleşme Süresi" secondValue={`${summary.durationMonths} ay`} /><Row firstLabel="Sonraki Ödeme Günü / IBAN" firstValue={`Her ayın ${summary.paymentDay}. günü · ${value(details.iban)}`} secondLabel="Başlangıç Tarihi" secondValue={details.startDate} /><Row firstLabel="Bitiş / Tahliye Uyarısı" firstValue={`${summary.endDate} / ${summary.noticeDate}`} /></tbody></table><div className="mt-3 rounded-md border-2 border-[#7c928b] bg-[#f4f9f6] px-3 py-2"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#47655d]">DASK poliçe numarası</p><p className="mt-1 font-semibold text-[#1c2524]">{value(details.daskPolicyNo)}</p></div></section>
    <section className="authority-document-section"><h3>KİRA SÖZLEŞMESİ TESLİM / DEMİRBAŞ EKİ</h3><table><tbody><Row firstLabel="Elektrik Sayaç No" firstValue={details.electricityMeterNo} secondLabel="Su Sayaç No" secondValue={details.waterMeterNo} /><Row firstLabel="Doğalgaz Sayaç No" firstValue={details.naturalGasMeterNo} /><Row firstLabel="Demirbaşlar ve Teslim Durumu" firstValue={rentalFixtureSummary(details)} /><Row firstLabel="Diğer Sayaç / Abonelik Notları" firstValue={details.meterNotes} /><Row firstLabel="Sözleşme Paketine Dahil Edilen Ekler" firstValue={selectedAppendices} />{details.hasGuarantor && <Row firstLabel="Kefil" firstValue={details.guarantorName} secondLabel="Kefil TCKN / Azami Tutar" secondValue={[details.guarantorIdentity, details.guarantorLimit].filter(Boolean).join(" / ")} />}</tbody></table></section>
    <section className="authority-document-conditions"><h3>SÖZLEŞME KOŞULLARI</h3><ol>{conditions.map((condition, index) => <li key={index}>{condition}</li>)}</ol><p className="authority-document-template-note">Koşul şablon sürümü: {RENTAL_CONDITIONS_TEMPLATE_VERSION}. Bu metin, kullanıcının sağladığı şablonun sözleşme anındaki offline snapshot’ıdır.</p></section>
    <section className={`authority-document-signatures rental-document-signatures rental-party-signature-boxes ${details.hasGuarantor ? "rental-with-guarantor" : ""}`}><div className="rental-party-signature-box"><p>KİRAYA VEREN</p><strong>{value(details.ownerName)}</strong><span>İmza</span></div><div className="rental-party-signature-box"><p>KİRACI</p><strong>{value(details.tenantName)}</strong><span>İmza</span></div>{details.hasGuarantor && <div className="rental-party-signature-box"><p>KEFİL</p><strong>{value(details.guarantorName)}</strong><span>İmza</span></div>}</section>
    <footer className="rental-advisor-trace">Düzenleme izi · {consultantInitials(details.consultantName)} · {value(details.startDate)} · Form: {value(contractNo)}</footer>
  </article>;
}
